import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  const services = [
    {
      id: 'rivning-badrum',
      category: 'rivning',
      additional_categories: ['badrum'],
      title_sv: 'Rivning badrum',
      description_sv: 'Komplett rivning av badrum inklusive kakel, klinker, golvbrunn och installationer. Vi hanterar allt från ytskikt till stomme beroende på behov.',
      title_en: 'Bathroom demolition',
      description_en: 'Complete bathroom demolition including tiles, floor drain and installations. We handle everything from surface layers to the frame as needed.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 1,
      search_keywords: 'rivning badrum riva badrumsrivning kakel klinker demolition bathroom',
    },
    {
      id: 'rivning-kok',
      category: 'rivning',
      additional_categories: ['kok'],
      title_sv: 'Rivning kök',
      description_sv: 'Rivning av kök inklusive skåp, bänkskivor, vitvaror och ytskikt. Förberedelse för nytt kök eller renovering.',
      title_en: 'Kitchen demolition',
      description_en: 'Kitchen demolition including cabinets, countertops, appliances and surface layers. Preparation for new kitchen or renovation.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 2,
      search_keywords: 'rivning kök riva köksrivning skåp bänkskiva demolition kitchen',
    },
    {
      id: 'rivning-innervaggar',
      category: 'rivning',
      title_sv: 'Rivning innerväggar',
      description_sv: 'Rivning av innerväggar i trä, gips eller lättbetong. Vi kontrollerar bärande konstruktioner och säkerställer korrekt rivning.',
      title_en: 'Interior wall demolition',
      description_en: 'Demolition of interior walls in wood, drywall or lightweight concrete. We check load-bearing structures and ensure correct demolition.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 3,
      search_keywords: 'rivning innerväggar vägg gips lättbetong demolition wall interior',
    },
    {
      id: 'rivning-golv',
      category: 'rivning',
      additional_categories: ['golv'],
      title_sv: 'Rivning golv',
      description_sv: 'Rivning av alla typer av golvmaterial: parkett, laminat, vinyl, klinker och betong. Professionell borttagning utan att skada underliggande konstruktion.',
      title_en: 'Floor demolition',
      description_en: 'Demolition of all types of flooring: parquet, laminate, vinyl, tiles and concrete. Professional removal without damaging underlying structure.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 4,
      search_keywords: 'rivning golv riva golvrivning parkett laminat vinyl klinker demolition floor',
    },
    {
      id: 'rivning-kakel-klinker',
      category: 'rivning',
      title_sv: 'Rivning kakel & klinker',
      description_sv: 'Professionell borttagning av kakel och klinker från väggar och golv. Vi minimerar skador på underliggande yta.',
      title_en: 'Tile removal',
      description_en: 'Professional removal of tiles from walls and floors. We minimize damage to the underlying surface.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 5,
      search_keywords: 'rivning kakel klinker plattor riva tile removal',
    },
    {
      id: 'rivning-totalrivning',
      category: 'rivning',
      title_sv: 'Totalrivning / stomrent',
      description_sv: 'Komplett rivning ner till stomme. Allt material avlägsnas – ytskikt, installationer, innerväggar. Perfekt inför totalrenovering.',
      title_en: 'Full strip-out',
      description_en: 'Complete demolition down to the frame. All materials removed – surfaces, installations, interior walls. Perfect before total renovation.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 6,
      search_keywords: 'totalrivning stomrent komplett rivning strip-out full demolition',
    },
    {
      id: 'rivning-haltagning',
      category: 'rivning',
      title_sv: 'Håltagning betong/tegel',
      description_sv: 'Precisionshåltagning i betong, tegel och sten för rör, ventilation, kabeldragning och fönster. Kärnborrning och sågning.',
      title_en: 'Concrete/brick core drilling',
      description_en: 'Precision core drilling in concrete, brick and stone for pipes, ventilation, cabling and windows.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'båda',
      is_active: true,
      sort_order: 7,
      search_keywords: 'håltagning betong tegel kärnborrning sågning core drilling concrete brick',
    },
    {
      id: 'rivning-tak-innertak',
      category: 'rivning',
      title_sv: 'Rivning innertak',
      description_sv: 'Rivning av innertak inklusive gipsskivor, akustikplattor och underliggande konstruktion. Förberedelse för nytt tak.',
      title_en: 'Ceiling demolition',
      description_en: 'Ceiling demolition including drywall, acoustic panels and underlying structure. Preparation for new ceiling.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 8,
      search_keywords: 'rivning innertak tak gips akustik ceiling demolition',
    },
    {
      id: 'rivning-fasad',
      category: 'rivning',
      title_sv: 'Rivning fasad/utvändigt',
      description_sv: 'Rivning av fasadmaterial, puts, panel och utvändiga konstruktioner. Säker rivning med hänsyn till bärande delar.',
      title_en: 'Exterior demolition',
      description_en: 'Demolition of facade materials, plaster, panels and exterior structures. Safe demolition with consideration for load-bearing parts.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'utomhus',
      is_active: true,
      sort_order: 9,
      search_keywords: 'rivning fasad utvändig puts panel exterior demolition facade',
    },
    {
      id: 'rivning-garage',
      category: 'rivning',
      title_sv: 'Rivning garage/förråd',
      description_sv: 'Komplett rivning av garage, förråd, skjul och mindre byggnader. Inklusive bortforsling av rivningsmaterial.',
      title_en: 'Garage/shed demolition',
      description_en: 'Complete demolition of garages, storage sheds and smaller buildings. Including disposal of demolition materials.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'utomhus',
      is_active: true,
      sort_order: 10,
      search_keywords: 'rivning garage förråd skjul byggnad demolition garage shed',
    },
    {
      id: 'rivning-altan-terrass',
      category: 'rivning',
      title_sv: 'Rivning altan & terrass',
      description_sv: 'Rivning av altan, terrass, trädäck och tillhörande konstruktioner. Vi hanterar trä, komposit och betongkonstruktioner.',
      title_en: 'Deck/patio demolition',
      description_en: 'Demolition of decks, patios and associated structures. We handle wood, composite and concrete constructions.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'utomhus',
      is_active: true,
      sort_order: 11,
      search_keywords: 'rivning altan terrass trädäck deck patio demolition',
    },
    {
      id: 'rivning-bortforsling',
      category: 'rivning',
      title_sv: 'Bortforsling & container',
      description_sv: 'Professionell bortforsling av rivningsmaterial och byggsopor. Vi ordnar container, sortering och transport till återvinning.',
      title_en: 'Waste disposal & skip',
      description_en: 'Professional disposal of demolition materials and construction waste. We arrange skips, sorting and transport to recycling.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'båda',
      is_active: true,
      sort_order: 12,
      search_keywords: 'bortforsling container byggsopor rivningsmaterial avfall waste disposal skip',
    },
    {
      id: 'rivning-asbestsanering',
      category: 'rivning',
      title_sv: 'Asbestsanering',
      description_sv: 'Certifierad asbestsanering enligt Arbetsmiljöverkets regler. Provtagning, rivning och säker omhändertagning av asbesthaltigt material.',
      title_en: 'Asbestos removal',
      description_en: 'Certified asbestos removal according to Swedish Work Environment Authority regulations. Sampling, demolition and safe disposal of asbestos-containing materials.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'båda',
      is_active: true,
      sort_order: 13,
      search_keywords: 'asbestsanering asbest sanering certifierad asbestos removal certified',
    },
    {
      id: 'rivning-vattenskadat',
      category: 'rivning',
      title_sv: 'Rivning vattenskadat material',
      description_sv: 'Akut och planerad rivning av vattenskadat material. Vi identifierar skadeomfattningen och river allt fuktskadat material för att förhindra mögel.',
      title_en: 'Water damage tearout',
      description_en: 'Emergency and planned removal of water-damaged materials. We identify the extent of damage and remove all moisture-damaged material to prevent mold.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'hourly',
      rot_eligible: true,
      rut_eligible: false,
      location: 'inomhus',
      is_active: true,
      sort_order: 14,
      search_keywords: 'rivning vattenskada fuktskada mögel akut water damage tearout mold',
    },
    {
      id: 'rivning-eldstad',
      category: 'rivning',
      title_sv: 'Rivning eldstad/skorsten',
      description_sv: 'Rivning av eldstäder, kakelugnar, öppna spisar och skorstenar. Vi hanterar tunga material säkert och kontrollerar bärande konstruktioner.',
      title_en: 'Fireplace/chimney demolition',
      description_en: 'Demolition of fireplaces, tiled stoves, open fires and chimneys. We handle heavy materials safely and check load-bearing structures.',
      base_price: 958,
      price_unit: 'kr/h',
      price_type: 'quote',
      rot_eligible: true,
      rut_eligible: false,
      location: 'båda',
      is_active: true,
      sort_order: 15,
      search_keywords: 'rivning eldstad skorsten kakelugn öppen spis fireplace chimney demolition',
    },
  ]

  const { data, error } = await supabase
    .from('services')
    .upsert(services, { onConflict: 'id', ignoreDuplicates: true })
    .select('id')

  if (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  return new Response(JSON.stringify({ success: true, count: data?.length || 0, ids: data?.map(d => d.id) }), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
})
