import type { CopyKey } from './keys';

export const en: Record<CopyKey, string> = {
  // Navigation
  'nav.home': 'Home',
  'nav.services': 'Services',
  'nav.smartHome': 'Smart Home',
  'nav.references': 'References',
  'nav.about': 'About us',
  'nav.contact': 'Contact',
  'nav.myFixco': 'My Fixco',
  'nav.adminPanel': 'Admin Panel',
  
  // Trust chips
  'chips.f_skatt': 'F-tax',
  'chips.insured': 'Insured',
  'chips.start_lt_5': 'Start within < 5 days',
  'chips.fixed_price': 'Fixed price',
  'chips.rot_50': 'ROT deduction 50%',
  'chips.rut_50': 'RUT deduction 50%',
  'chips.transparent': 'Transparent pricing',
  'chips.free_quote': 'Free quote',
  'chips.we_handle_rot': 'We handle ROT',
  'chips.happy_customers': '2000+ happy customers',
  'chips.fast_support': 'Fast support',
  'chips.certified': 'Certified',
  'chips.warranty': 'Warranty',
  'chips.eco_friendly': 'Eco-friendly',
  'chips.quick_response': 'Quick response',
  'chips.quality_work': 'Quality work',
  'chips.more': 'more',
  
  // Buttons & CTAs
  'cta.book_now': 'Book now',
  'cta.request_quote': 'Request a quote',
  'cta.call_us': 'Call us',
  'cta.login': 'Login',
  'cta.get_quote': 'Get quote',
  'cta.see_all': 'See all →',
  'cta.book_direct': 'Book direct',
  'cta.book_installation': 'Book Installation',
  'cta.free_consultation': 'Free consultation',
  
  // Services
  'services.title': 'Our services',
  'services.subtitle': 'From small repairs to major construction projects – we have the expertise and experience to deliver professional solutions in all areas.',
  'services.rot_benefit': 'Take advantage of the ROT deduction and save 50%.',
  'services.choose_category': 'Choose category',
  'services.category_description': 'Find the right service for your home quickly and easily. We offer everything from small repairs to major renovation projects.',
  'services.all_services': 'All services',
  'services.all_services_description': 'Search, filter and compare our services quickly and easily. Everything you need is visible immediately - no hidden menus.',
  'services.visualize_project': 'Visualize your project',
  'services.visualize_description': 'See how your home could look after renovation with our advanced tools.',
  'services.ai_assistant': 'AI Project Assistant',
  'services.ai_description': 'Get personalized recommendations to optimize your home with AI analysis, ROT deduction and environmental thinking.',
  'services.rot_section_title': 'ROT deduction – Save 50% on labor costs',
  'services.rot_what_title': 'What is ROT deduction?',
  'services.rot_what_description': 'ROT deduction gives you 50% discount on labor costs for repair, conversion and extension as well as maintenance work in your home. The deduction is made directly from your tax.',
  'services.rot_we_handle_title': 'We handle everything',
  'services.rot_we_handle_description': 'Fixco handles all ROT applications for you. You just need to approve the work, we take care of the rest. Simple and convenient.',
  'services.request_quote_rot': 'Request quote with ROT deduction',
  'services.count': 'services',
  'services.ordinary_price': 'Ordinary price:',
  'services.with_rot': 'With ROT deduction:',
  'services.savings': 'Save',
  'services.energy_efficient': 'Energy efficient solution',
  'services.eco_materials': 'Eco-friendly materials',
  'services.ai_optimized': 'AI-optimized',
  'services.rot_eligible': 'ROT eligible',
  'services.eco_score': 'Eco Score',
  'services.preview': 'Preview',
  'services.show_3d': 'Show in 3D',
  'services.incl_install': 'Incl. installation & setup',
  'services.quote_after_inspection': 'Quote after inspection',
  
  // Smart Home
  'smartHome.title': 'Smart Home Automation',
  'smartHome.subtitle': 'Control and optimize your home with AI and IoT technology',
  'smartHome.energy_reduction': 'Energy consumption',
  'smartHome.connected_devices': 'Connected devices',
  'smartHome.automation': 'Automation',
  'smartHome.savings': 'Savings',
  'smartHome.products_title': 'Smart Home - Real Products',
  'smartHome.products_subtitle': 'We only install proven, market-leading smart home products from the world\'s largest manufacturers. All products come with full warranty and professional installation.',
  'smartHome.all_products': 'All Smart Home Products',
  'smartHome.loading': 'Loading products...',
  'smartHome.no_products': 'No products found',
  'smartHome.market_leaders': 'Market Leading Brands',
  'smartHome.full_warranty': 'Full Warranty',
  'smartHome.professional_install': 'Professional Installation',
  'smartHome.ai_optimized': 'AI-Optimized',
  'smartHome.choose_category': 'Choose Product Category',
  'smartHome.main_features': 'Main features:',
  'smartHome.smart_features': 'Smart Features:',
  'smartHome.installation_setup': 'Incl. installation & setup',
  'smartHome.years_warranty': '2 years full warranty',
  'smartHome.contact_for_info': 'Contact us for installation and more information!',
  
  // Categories
  'categories.all': 'All Products',
  'categories.security': 'Security & Locks',
  'categories.lighting': 'Smart Lighting',
  'categories.climate': 'Climate & Heating',
  'categories.cleaning': 'Robots',
  'categories.garden': 'Garden',
  'categories.entertainment': 'Entertainment',
  'categories.all_desc': 'Complete smart home experience',
  'categories.security_desc': 'Protect your home',
  'categories.lighting_desc': 'Energy efficient lighting',
  'categories.climate_desc': 'Temperature control',
  'categories.cleaning_desc': 'Automatic cleaning',
  'categories.garden_desc': 'Smart garden care',
  'categories.entertainment_desc': 'Speakers & Home Cinema',
  
  // Service Categories (keep both versions for compatibility)
  'serviceCategories.el': 'Electrical',
  'serviceCategories.vvs': 'Plumbing',
  'serviceCategories.snickeri': 'Carpentry',
  'serviceCategories.montering': 'Assembly',
  'serviceCategories.tradgard': 'Garden',
  'serviceCategories.stadning': 'Cleaning',
  'serviceCategories.markarbeten': 'Groundwork',
  'serviceCategories.tekniska-installationer': 'Technical installations',
  'serviceCategories.flytt': 'Moving',

  // Service Categories Extended
  'serviceCategories.el.title': 'Electrical',
  'serviceCategories.el.description': 'Installation, repair and maintenance of electrical systems',
  'serviceCategories.vvs.title': 'Plumbing', 
  'serviceCategories.vvs.description': 'Pipes, water and drainage',
  'serviceCategories.snickeri.title': 'Carpentry',
  'serviceCategories.snickeri.description': 'Custom wood solutions',
  'serviceCategories.montering.title': 'Assembly',
  'serviceCategories.montering.description': 'Furniture and appliances',
  'serviceCategories.tradgard.title': 'Garden',
  'serviceCategories.tradgard.description': 'Maintenance and landscaping',
  'serviceCategories.stadning.title': 'Cleaning',
  'serviceCategories.stadning.description': 'Home service and cleaning',
  'serviceCategories.markarbeten.title': 'Groundwork',
  'serviceCategories.markarbeten.description': 'Excavation and landscaping',
  'serviceCategories.tekniska-installationer.title': 'Technical installations',
  'serviceCategories.tekniska-installationer.description': 'Network, security and IT support',
  'serviceCategories.flytt.title': 'Moving',
  'serviceCategories.flytt.description': 'Transport and moving assistance',
  
  // Filter UI
  'filter.search_placeholder': 'Search for service, e.g. "dimmer", "IKEA", "dishwasher"',
  'filter.all_services': 'All services',
  'filter.all_prices': 'All prices',
  'filter.hourly_rate': 'Hourly rate',
  'filter.fixed_price': 'Fixed price',
  'filter.request_quote': 'Request quote',
  'filter.all_locations': 'All locations',
  'filter.indoor': 'Indoor',
  'filter.outdoor': 'Outdoor',
  'filter.clear': 'Clear',
  'filter.specialty_areas': 'Specialty areas:',
  'filter.searching': 'Search:',
  'filter.services_found': 'services found',
  'filter.no_services_rot_rut': 'No services are eligible for',
  'filter.with_current_filters': 'with your current filters.',
  'filter.show_all_services': 'Show all services',
  
  // Price display
  'price.saves_with_rot': 'Saves',
  'price.saves_with_rut': 'Saves', 
  'price.with_rot_discount': 'with ROT',
  'price.with_rut_discount': 'with RUT',
  'price.show_rot_prices': 'Show prices with ROT discount (50% off)',
  'filter.clear_other_filters': 'Clear other filters',
  'filter.no_services_general': 'No services matched your search criteria',
  'filter.clear_filters_try_again': 'Clear filters and try again',
  
  // Service texts that need translation
  'service_text.quote_for': 'Quote request for',
  'service_text.booking_for': 'Booking for',
  'service_text.started': 'started!',
  'service_text.sent': 'sent!',
  
  // Individual service translations - EL
  'service.el-1.title': 'Replace Wall Outlet',
  'service.el-1.description': 'Replace wall outlets with newer models. Quantity selected during booking',
  'service.el-2.title': 'Replace Switch & Dimmer',
  'service.el-2.description': 'Installation of new switches and dimmers. Quantity selected during booking',
  'service.el-3.title': 'Install Ceiling Fixture/Pendant',
  'service.el-3.description': 'Installation of ceiling fixtures and pendant lamps. Quantity selected during booking',
  'service.el-4.title': 'Install Spotlights',
  'service.el-4.description': 'Installation of spotlights in ceiling. Quantity selected during booking (typically 0.5-1h per 4-6 pcs)',
  'service.el-5.title': 'Outdoor Lighting',
  'service.el-5.description': 'Installation of facade and garden lighting. Type selected during booking',
  'service.el-6.title': 'Install Ground Fault Breaker',
  'service.el-6.description': 'Installation of ground fault circuit breaker for safety',
  'service.el-7.title': 'Electrical Troubleshooting',
  'service.el-7.description': 'Diagnostics and troubleshooting of electrical installations (typically 1-2 hours)',
  'service.el-8.title': 'Install New Electrical Point',
  'service.el-8.description': 'Installation of new electrical point. Room selected during booking',
  'service.el-9.title': 'Mount TV Wall Bracket & Cable Management',
  'service.el-9.description': 'Installation of TV bracket with cable management',
  'service.el-10.title': 'New Power to Kitchen Island',
  'service.el-10.description': 'Electrical installation for kitchen island with outlets',
  'service.el-11.title': 'New Electrical Circuit',
  'service.el-11.description': 'Installation of new electrical circuit in the panel',
  
  // Individual service translations - VVS
  'service.vvs-1.title': 'Replace Faucet',
  'service.vvs-1.description': 'Replace faucet. Room/type selected during booking',
  'service.vvs-2.title': 'Replace Toilet',
  'service.vvs-2.description': 'Replace toilet with installation',
  'service.vvs-3.title': 'Replace Water Trap & Drain Kit',
  'service.vvs-3.description': 'Replace water trap and drain assembly',
  'service.vvs-4.title': 'Install Dishwasher',
  'service.vvs-4.description': 'Installation and connection of dishwasher',
  'service.vvs-5.title': 'Install Washing Machine',
  'service.vvs-5.description': 'Installation and connection of washing machine',
  'service.vvs-6.title': 'Install Shower Mixer',
  'service.vvs-6.description': 'Installation of new shower mixer',
  'service.vvs-7.title': 'Install Ceiling Shower',
  'service.vvs-7.description': 'Installation of ceiling shower with pipes',
  'service.vvs-8.title': 'Replace Radiator',
  'service.vvs-8.description': 'Replace radiator with connections',
  'service.vvs-9.title': 'Replace Thermostat Valve',
  'service.vvs-9.description': 'Replace thermostat valve on radiator',
  'service.vvs-10.title': 'Seal Pipe Connections',
  'service.vvs-10.description': 'Seal leaking pipe connections',
  'service.vvs-11.title': 'Fix Dripping',
  'service.vvs-11.description': 'Repair dripping faucets',
  'service.vvs-12.title': 'Floor Drain Replacement',
  'service.vvs-12.description': 'Replace floor drain with connections',
  'service.vvs-13.title': 'Bathroom Renovation',
  'service.vvs-13.description': 'Complete bathroom renovation',
  
  // Individual service translations - SNICKERI
  'service.snickeri-1.title': 'Custom Built Wardrobe',
  'service.snickeri-1.description': 'Manufacturing of custom built wardrobe. Size selected during booking',
  'service.snickeri-2.title': 'Kitchen Doors & Countertops',
  'service.snickeri-2.description': 'Replace kitchen doors and install countertops',
  'service.snickeri-3.title': 'Interior & Shelving',
  'service.snickeri-3.description': 'Manufacturing of custom interior and shelving systems',
  'service.snickeri-4.title': 'Door Installation',
  'service.snickeri-4.description': 'Installation of interior doors with frames and handles',
  'service.snickeri-5.title': 'Trim & Finish',
  'service.snickeri-5.description': 'Installation of floor, ceiling and door trim',
  
  // Individual service translations - MONTERING
  'service.montering-1.title': 'IKEA Furniture',
  'service.montering-1.description': 'Assembly of all types of IKEA furniture',
  'service.montering-2.title': 'TV Wall Mount',
  'service.montering-2.description': 'Safe mounting of TV on wall',
  'service.montering-3.title': 'Pictures and Mirrors',
  'service.montering-3.description': 'Hanging of pictures, mirrors and art',
  'service.montering-4.title': 'Appliances (fridge, freezer, oven)',
  'service.montering-4.description': 'Installation and connection of appliances',
  
  // Individual service translations - TRADGARD
  'service.tradgard-1.title': 'Lawn Mowing',
  'service.tradgard-1.description': 'Regular lawn mowing and edge trimming',
  'service.tradgard-2.title': 'Hedge Trimming',
  'service.tradgard-2.description': 'Pruning of hedges and bushes',
  'service.tradgard-3.title': 'Weed Removal',
  'service.tradgard-3.description': 'Removal of weeds from flower beds and walkways',
  'service.tradgard-4.title': 'Planting and Landscaping',
  'service.tradgard-4.description': 'Planting of plants and landscaping of flower beds',
  'service.tradgard-5.title': 'Leaf Raking',
  'service.tradgard-5.description': 'Removal of leaves from lawn and flower beds',
  'service.tradgard-6.title': 'Snow Shoveling/Sanding',
  'service.tradgard-6.description': 'Snow removal and anti-slip treatment of driveways and walkways',
  
  // Individual service translations - STADNING
  'service.stadning-1.title': 'Regular Home Cleaning',
  'service.stadning-1.description': 'Regular cleaning of the home',
  'service.stadning-2.title': 'Move-out Cleaning',
  'service.stadning-2.description': 'Thorough cleaning when moving',
  'service.stadning-3.title': 'Construction Cleaning',
  'service.stadning-3.description': 'Cleaning after renovation and construction work',
  'service.stadning-4.title': 'Window Cleaning',
  'service.stadning-4.description': 'Professional window cleaning inside and outside',
  'service.stadning-5.title': 'Deep Cleaning Kitchen/Bathroom',
  'service.stadning-5.description': 'Thorough cleaning of kitchen or bathroom',
  'service.stadning-6.title': 'Office Cleaning (B2B)',
  'service.stadning-6.description': 'Cleaning of office premises - business customer',
  
  // Individual service translations - MARKARBETEN
  'service.markarbeten-1.title': 'Excavation',
  'service.markarbeten-1.description': 'Digging and excavation work for foundations and utilities',
  'service.markarbeten-2.title': 'Drainage',
  'service.markarbeten-2.description': 'Installation of drainage systems',
  'service.markarbeten-3.title': 'Paving',
  'service.markarbeten-3.description': 'Laying of tiles and stone surfaces',
  'service.markarbeten-4.title': 'Masonry',
  'service.markarbeten-4.description': 'Masonry work and stone setting',
  
  // Individual service translations - TEKNISKA INSTALLATIONER
  'service.tekniska-1.title': 'Network & IT',
  'service.tekniska-1.description': 'Installation of network and IT infrastructure',
  'service.tekniska-2.title': 'Alarm Systems',
  'service.tekniska-2.description': 'Installation of security alarms and surveillance systems',
  'service.tekniska-3.title': 'Audio & Video',
  'service.tekniska-3.description': 'Installation of home theater and audio systems',
  
  // Individual service translations - FLYTT
  'service.flytt-1.title': 'Moving Help',
  'service.flytt-1.description': 'Help with heavy lifting and transport',
  'service.flytt-2.title': 'Packing',
  'service.flytt-2.description': 'Professional packing of your belongings',
  'service.flytt-3.title': 'Moving Transport',
  'service.flytt-3.description': 'Transport of furniture and belongings',
  'service.flytt-4.title': 'Recycling Clearance',
  'service.flytt-4.description': 'Clearance and transport to recycling',
  'service.flytt-5.title': 'Furniture Assembly/Disassembly',
  'service.flytt-5.description': 'Disassembly and assembly of furniture during moves',
  
  // Project visualization texts
  'project.eco_performance': 'This project has high environmental performance thanks to energy efficient materials and methods.',
  'project.ai_results': 'AI-generated results',
  'project.environmental_impact': 'Environmental impact analysis',
  'project.rot_rut_optimization': 'ROT/RUT optimization',
  
  // Pages
  'pages.about.title': 'About Fixco',
  'pages.about.subtitle': 'Your partner for professional craftsmanship and construction services in Uppsala and Stockholm.',
  'pages.about.history_title': 'Our history',
  'pages.about.history_text': 'Fixco was founded with a simple vision: to make quality home services accessible, simple and affordable for everyone. Our experienced craftsmen have worked to deliver the highest quality since the start, and the experience we have created in the construction and renovation industry in the region.',
  'pages.about.customers': 'Satisfied customers',
  'pages.about.days_start': 'We start within < 5 days',
  'pages.about.years_exp': '5 years',
  'pages.references.title': 'References',
  
  // Service Detail Page
  'serviceDetail.notFound': 'Service not found',
  'serviceDetail.backToServices': 'Back to services',
  'serviceDetail.requestQuote': 'Request quote',
  'serviceDetail.callUs': 'Call 08-123 456 78',
  'serviceDetail.differentServices': 'Different services',
  'serviceDetail.projectStart': 'Project start',
  'serviceDetail.guaranteed': 'Guaranteed',
  'serviceDetail.customerSatisfaction': 'customer satisfaction',
  'serviceDetail.allOurServices': 'All our',
  'serviceDetail.specializedServices': 'specialized services with transparent pricing.',
  'serviceDetail.allPricesInclude': 'All prices include VAT and can be combined with ROT/RUT deductions for 50% discount.',
  'serviceDetail.availableIn': 'Available in Uppsala & Stockholm',
  'serviceDetail.previous': 'Previous',
  'serviceDetail.next': 'Next',
  'serviceDetail.customersAlsoBook': 'Customers also book',
  'serviceDetail.relatedServices': 'Related services often combined with',
  'serviceDetail.relatedService': 'Related service',
  'serviceDetail.readyToStart': 'Ready to start your',
  'serviceDetail.contactToday': 'Contact us today for a free consultation. We help you from idea to finished result.',
  'serviceDetail.requestFreeQuote': 'Request free quote',
  'serviceDetail.quickStart': 'Quick start',
  'serviceDetail.canStartWithin': 'We can start your project within 24-48 hours',
  'serviceDetail.secureGuarantee': 'Secure guarantee',
  'serviceDetail.yearsGuarantee': '2 years guarantee on all work performed',
  'serviceDetail.rotRutHandling': 'ROT/RUT handling',
  'serviceDetail.weHandleAll': 'We handle all deductions and administration',
  'serviceDetail.days': 'days',
  'serviceDetail.discount': 'discount',
  'serviceDetail.taxAndInsurance': 'tax & insurance', 
  'serviceDetail.startWithinDays': 'Start within < 5 days',
  
  // Contact Page Extended  
  'pages.contact.bookVisit': 'Book visit',

  // Contact Page
  'pages.contact.title': 'Contact Us',
  'pages.contact.subtitle': 'Get a free quote within 24 hours. We work in Uppsala & Stockholm counties (nationwide for larger projects).',
  'pages.contact.quickResponse': 'Quick response',
  'pages.contact.quickResponseDesc': 'Response within 2 hours',
  'pages.contact.freeQuote': 'Free quote',
  'pages.contact.freeQuoteDesc': 'No hidden costs',
  'pages.contact.localService': 'Local service',
  'pages.contact.localServiceDesc': 'Uppsala & Stockholm',
  'pages.contact.requestQuote': 'Request Quote',
  'pages.contact.formDescription': 'Fill out the form and we\'ll get back to you within 24 hours with a free and detailed quote.',
  'pages.contact.name': 'Name',
  'pages.contact.phone': 'Phone',
  'pages.contact.email': 'Email',
  'pages.contact.address': 'Project address',
  'pages.contact.serviceType': 'Type of service',
  'pages.contact.selectService': 'Select service',
  'pages.contact.projectDescription': 'Project description',
  'pages.contact.projectPlaceholder': 'Describe your project as detailed as possible. What work needs to be done? Approximate timeframe? Any special requirements?',
  'pages.contact.sendRequest': 'Send request',
  'pages.contact.sending': 'Sending...',
  'pages.contact.consent': 'By submitting the form, you agree that we may contact you regarding your request.',
  'pages.contact.contactInfo': 'Contact Information',
  'pages.contact.telephone': 'Phone',
  'pages.contact.callNow': 'Call now for urgent matters',
  'pages.contact.emailContact': 'Email',
  'pages.contact.responseTime': 'Response within 2 hours',
  'pages.contact.operatingArea': 'Service Area',
  'pages.contact.areaDesc': 'Nationwide for larger projects',
  'pages.contact.openingHours': 'Opening Hours',
  'pages.contact.mondayFriday': 'Monday - Friday',
  'pages.contact.saturday': 'Saturday',
  'pages.contact.sunday': 'Sunday',
  'pages.contact.closed': 'Closed',
  'pages.contact.emergencyService': 'Emergency service:',
  'pages.contact.emergencyDesc': 'Call for urgent leaks and electrical issues',
  'pages.contact.whyChoose': 'Why choose Fixco?',
  'pages.contact.startIn24h': 'Start within 24 hours',
  'pages.contact.rotDeduction': 'ROT deduction - only 480 SEK/h',
  'pages.contact.guaranteedQuality': 'Guaranteed quality',
  'pages.contact.freeQuotes': 'Free quotes',
  'pages.contact.fieldsMissing': 'Fields missing',
  'pages.contact.fillAllFields': 'Please fill in all required fields.',
  'pages.contact.thankYou': 'Thank you for your request!',
  'pages.contact.responseIn24h': 'We will get back to you within 24 hours with a free quote.',
  'pages.contact.somethingWrong': 'Something went wrong',
  'pages.contact.tryAgain': 'Please try again or call us directly.',

  // FAQ Page
  'pages.faq.title': 'Frequently Asked Questions',
  'pages.faq.subtitle': 'Here you can find answers to the most common questions about our services, prices, and work methods.',
  'pages.faq.askQuestion': 'Ask a question',
  'pages.faq.callUs': 'Call us: 08-123 456 78',
  'pages.faq.rotPrices': 'ROT Deduction & Prices',
  'pages.faq.bookingTime': 'Booking & Time Frames',
  'pages.faq.qualityGuarantee': 'Quality & Guarantee',
  'pages.faq.practicalQuestions': 'Practical Questions',
  'pages.faq.noAnswer': 'Can\'t find an answer to your question?',
  'pages.faq.contactUs': 'Contact us and we\'ll be happy to help with your questions and concerns.',
  'pages.faq.sendMessage': 'Send message',

  // About Page Extended
  'pages.about.values': 'Our Values',
  'pages.about.speed': 'Speed',
  'pages.about.speedDesc': 'We start projects within 24 hours and always deliver on time. Your home is important and we respect your time.',
  'pages.about.quality': 'Quality',
  'pages.about.qualityDesc': 'All our craftsmen are certified and we only use materials of the highest quality. We guarantee all our work.',
  'pages.about.transparency': 'Transparency',
  'pages.about.transparencyDesc': 'No hidden costs, clear quotes, and open communication throughout the project. You always know what you\'re paying for.',
  'pages.about.coverageArea': 'Our Service Area',
  'pages.about.coverageDesc': 'We cover all of Uppsala municipality and Stockholm county with our services. Our experienced craftsmen can be with you shortly for both urgent matters and planned projects.',
  'pages.about.readyToStart': 'Ready to get started?',
  'pages.about.contactToday': 'Contact us today for a free consultation and quote. We\'re here to help you realize your projects.',

  // Privacy Page
  'pages.privacy.title': 'Privacy Policy',
  'pages.privacy.description': 'We value your privacy. This page is a placeholder and will be updated with complete policy text.',

  // Terms Page
  'pages.terms.title': 'Terms of Service',
  'pages.terms.description': 'Here we describe the terms that apply to the use of our services. This page is a placeholder and may be updated with complete legal content later.',

  // ROT Info Page
  'pages.rot.title': 'ROT Tax Deduction with Fixco',
  'pages.rot.subtitle': 'Save 50% on labor costs with ROT tax deduction. We handle all the paperwork for you.',
  'pages.rot.hero.title': 'Save 50% with ROT Tax Deduction',
  'pages.rot.hero.subtitle': 'We help you get maximum ROT tax deduction and handle all applications for you. Simple.',
  'pages.rot.hero.bookVisit': 'Book home visit',
  'pages.rot.hero.phone': 'Call: 08-123 456 78',
  'pages.rot.what.title': 'What is ROT tax deduction?',
  'pages.rot.what.description1': 'ROT tax deduction is a tax reduction that gives you 50% discount on labor costs for repairs, renovations and maintenance work in your home.',
  'pages.rot.what.description2': 'The deduction is made directly from your taxes and you can get a maximum of 50,000 SEK per person per year. For couples, that\'s a total of 100,000 SEK per household.',
  'pages.rot.what.benefit1': '50% discount on labor costs',
  'pages.rot.what.benefit2': 'Max 50,000 SEK per person per year',
  'pages.rot.what.benefit3': 'Applies to permanent residences',
  'pages.rot.what.benefit4': 'We handle all applications',
  'pages.rot.what.discount': '50% Discount',
  'pages.rot.what.discountDescription': 'You only pay half the labor cost when using the ROT tax deduction',
  'pages.rot.examples.title': 'Savings examples',
  'pages.rot.examples.service1': 'Kitchen faucet replacement',
  'pages.rot.examples.service2': 'Toilet replacement',
  'pages.rot.examples.service3': 'Kitchen renovation',
  'pages.rot.examples.work1': '2 hours of work',
  'pages.rot.examples.work2': 'Fixed price',
  'pages.rot.examples.work3': '40 hours of work',
  'pages.rot.examples.savings': 'You save:',
  'pages.rot.examples.price': 'Price:',
  'pages.rot.examples.withRot': 'With ROT deduction:',
  'pages.rot.process.title': 'How it works - simple',
  'pages.rot.process.step1.title': 'We do the job',
  'pages.rot.process.step1.description': 'You book the service and we perform the work professionally according to quote.',
  'pages.rot.process.step2.title': 'We submit the application',
  'pages.rot.process.step2.description': 'We fill out and submit the ROT application to the Tax Agency for you. No hassle for you.',
  'pages.rot.process.step3.title': 'You pay discounted price',
  'pages.rot.process.step3.description': 'You pay only 50% of the labor cost directly to us. The rest you get back through taxes.',
  'pages.rot.qualifies.title': 'What qualifies for ROT?',
  'pages.rot.qualifies.yes.title': '✅ Qualifies for ROT',
  'pages.rot.qualifies.no.title': '❌ Does NOT qualify for ROT',
  'pages.rot.cta.title': 'Ready to save 50% on your project?',
  'pages.rot.cta.description': 'Book a free consultation and we\'ll help you get maximum ROT tax deduction.',
  'pages.rot.cta.bookNow': 'Book home visit now',
  'pages.rot.cta.requestQuote': 'Request quote',

  // RUT Info Page
  'pages.rut.title': 'RUT Tax Deduction with Fixco',
  'pages.rut.subtitle': 'Save 50% on labor costs for home services with RUT tax deduction. We handle all the paperwork for you.',
  'pages.rut.hero.title': 'Save 50% with RUT Tax Deduction',
  'pages.rut.hero.subtitle': 'We help you get maximum RUT tax deduction for home services and handle all applications for you. Simple.',
  'pages.rut.hero.bookVisit': 'Book home visit',
  'pages.rut.hero.phone': 'Call: 08-123 456 78',
  'pages.rut.what.title': 'What is RUT tax deduction?',
  'pages.rut.what.description1': 'RUT tax deduction is a tax reduction that gives you 50% discount on labor costs for cleaning, maintenance and laundry services in your home.',
  'pages.rut.what.description2': 'The deduction is made directly from your taxes and you can get a maximum of 50,000 SEK per person per year. For couples, that\'s a total of 100,000 SEK per household.',
  'pages.rut.what.benefit1': '50% discount on labor costs',
  'pages.rut.what.benefit2': 'Max 50,000 SEK per person per year',
  'pages.rut.what.benefit3': 'Applies to permanent residences',
  'pages.rut.what.benefit4': 'We handle all applications',
  'pages.rut.what.discount': '50% Discount',
  'pages.rut.what.discountDescription': 'You only pay half the labor cost when using the RUT tax deduction',
  'pages.rut.examples.title': 'Savings examples',
  'pages.rut.examples.service1': 'Home cleaning',
  'pages.rut.examples.service2': 'Window cleaning',
  'pages.rut.examples.service3': 'Construction cleaning',
  'pages.rut.examples.work1': '4 hours cleaning',
  'pages.rut.examples.work2': '2 hours work',
  'pages.rut.examples.work3': '8 hours work',
  'pages.rut.examples.savings': 'You save:',
  'pages.rut.examples.price': 'Price:',
  'pages.rut.examples.withRut': 'With RUT deduction:',
  'pages.rut.process.title': 'How it works - simple',
  'pages.rut.process.step1.title': 'We perform the service',
  'pages.rut.process.step1.description': 'You book home service and we perform the work professionally according to agreement.',
  'pages.rut.process.step2.title': 'We submit the application',
  'pages.rut.process.step2.description': 'We fill out and submit the RUT application to the Tax Agency for you. No hassle for you.',
  'pages.rut.process.step3.title': 'You pay discounted price',
  'pages.rut.process.step3.description': 'You pay only 50% of the labor cost directly to us. The rest you get back through taxes.',
  'pages.rut.qualifies.title': 'What qualifies for RUT?',
  'pages.rut.qualifies.yes.title': '✅ Qualifies for RUT',
  'pages.rut.qualifies.no.title': '❌ Does NOT qualify for RUT',
  'pages.rut.cta.title': 'Ready to save 50% on home services?',
  'pages.rut.cta.description': 'Book a free consultation and we\'ll help you get maximum RUT tax deduction.',
  'pages.rut.cta.bookNow': 'Book home visit now',
  'pages.rut.cta.requestQuote': 'Request quote',
  'home.comparison.title': 'Why choose Fixco?',
  'home.comparison.subtitle': 'Transparent comparison showing why thousands of customers choose us',
  'home.services.title': 'Our main services',
  'home.services.subtitle': 'From small repairs to large projects – we handle everything professionally',
  'home.services.viewAll': 'View all services'
};