import type { CopyKey } from './keys';

export const sv: Record<CopyKey, string> = {
  // Navigation
  'nav.home': 'Hem',
  'nav.services': 'Tjänster', 
  'nav.smartHome': 'Smart Hem',
  'nav.references': 'Referenser',
  'nav.about': 'Om oss',
  'nav.contact': 'Kontakt',
  'nav.myFixco': 'Mitt Fixco',
  'nav.adminPanel': 'Adminpanel',
  
  // Trust chips
  'chips.f_skatt': 'F-skatt',
  'chips.insured': 'Försäkrade',
  'chips.start_lt_5': 'Start inom < 5 dagar',
  'chips.fixed_price': 'Fast pris',
  'chips.rot_50': 'ROT-avdrag 50%',
  'chips.rut_50': 'RUT-avdrag 50%',
  'chips.transparent': 'Transparent pris',
  'chips.free_quote': 'Kostnadsfri offert',
  'chips.we_handle_rot': 'Vi sköter ROT',
  'chips.happy_customers': '2000+ nöjda kunder',
  'chips.fast_support': 'Snabb support',
  'chips.certified': 'Certifierade',
  'chips.warranty': 'Garanti',
  'chips.eco_friendly': 'Miljövänligt',
  'chips.quick_response': 'Snabb respons',
  'chips.quality_work': 'Kvalitetsarbete',
  'chips.more': 'fler',
  
  // Buttons & CTAs
  'cta.book_now': 'Boka nu',
  'cta.request_quote': 'Begär offert',
  'cta.call_us': 'Ring oss',
  'cta.login': 'Logga in',
  'cta.get_quote': 'Få offert',
  'cta.see_all': 'Se alla →',
  'cta.book_direct': 'Boka direkt',
  'cta.book_installation': 'Boka Installation',
  'cta.free_consultation': 'Kostnadsfri konsultation',
  
  // Services
  'services.title': 'Våra tjänster',
  'services.subtitle': 'Från små reparationer till stora byggnationer – vi har expertisen och erfarenheten för att leverera professionella lösningar inom alla områden.',
  'services.rot_benefit': 'Utnyttja ROT-avdraget och spara 50%.',
  'services.choose_category': 'Välj kategori',
  'services.category_description': 'Hitta rätt tjänst för ditt hem snabbt och enkelt. Vi erbjuder allt från små reparationer till stora renoveringsprojekt.',
  'services.all_services': 'Alla tjänster',
  'services.all_services_description': 'Sök, filtrera och jämför våra tjänster snabbt och enkelt. Allt du behöver är synligt direkt - inga gömda menyer.',
  'services.visualize_project': 'Visualisera ditt projekt',
  'services.visualize_description': 'Se hur ditt hem kan se ut efter renovering med våra avancerade verktyg.',
  'services.ai_assistant': 'AI Projektassistent',
  'services.ai_description': 'Få personliga rekommendationer för att optimera ditt hem med AI-analys, ROT-avdrag och miljötänk.',
  'services.rot_section_title': 'ROT-avdraget – Spara 50% på arbetskostnaden',
  'services.rot_what_title': 'Vad är ROT-avdrag?',
  'services.rot_what_description': 'ROT-avdrag ger dig 50% rabatt på arbetskostnaden för reparation, om- och tillbyggnad samt underhållsarbeten i din bostad. Avdraget görs direkt från din skatt.',
  'services.rot_we_handle_title': 'Vi sköter allt',
  'services.rot_we_handle_description': 'Fixco hanterar alla ROT-ansökningar åt dig. Du behöver bara godkänna arbetet, resten ordnar vi. Enkelt och bekvämt.',
  'services.request_quote_rot': 'Begär offert med ROT-avdrag',
  'services.count': 'tjänster',
  'services.ordinary_price': 'Ordinarie pris:',
  'services.with_rot': 'Med ROT-avdrag:',
  'services.savings': 'Sparar',
  'services.energy_efficient': 'Energieffektiv lösning',
  'services.eco_materials': 'Miljövänliga material', 
  'services.ai_optimized': 'AI-optimerad',
  'services.rot_eligible': 'ROT-berättigad',
  'services.eco_score': 'Eco Score',
  'services.preview': 'Förhandsvisning',
  'services.show_3d': 'Visa i 3D',
  'services.incl_install': 'Inkl. installation & setup',
  'services.quote_after_inspection': 'Prisuppgift efter besiktning',
  
  // Smart Home
  'smartHome.title': 'Smart Hemautomation',
  'smartHome.subtitle': 'Styr och optimera ditt hem med AI och IoT-teknik',
  'smartHome.energy_reduction': 'Energiförbrukning',
  'smartHome.connected_devices': 'Anslutna enheter',
  'smartHome.automation': 'Automatisering',
  'smartHome.savings': 'Besparingar',
  'smartHome.products_title': 'Smart Hem - Verkliga Produkter',
  'smartHome.products_subtitle': 'Vi installerar endast beprövade, marknadsledande smart hem-produkter från världens största tillverkare. Alla produkter kommer med fullständig garanti och professionell installation.',
  'smartHome.all_products': 'Alla Smart Hem-Produkter',
  'smartHome.loading': 'Laddar produkter...',
  'smartHome.no_products': 'Inga produkter hittades',
  'smartHome.market_leaders': 'Marknadsledande Märken',
  'smartHome.full_warranty': 'Fullständig Garanti',
  'smartHome.professional_install': 'Professionell Installation',
  'smartHome.ai_optimized': 'AI-Optimerad',
  'smartHome.choose_category': 'Välj Produktkategori',
  'smartHome.main_features': 'Huvudfunktioner:',
  'smartHome.smart_features': 'Smarta Funktioner:',
  'smartHome.installation_setup': 'Inkl. installation & setup',
  'smartHome.years_warranty': '2 års fullgaranti',
  'smartHome.contact_for_info': 'Kontakta oss för installation och mer information!',
  
  // Categories
  'categories.all': 'Alla Produkter',
  'categories.security': 'Säkerhet & Lås',
  'categories.lighting': 'Smart Belysning',
  'categories.climate': 'Klimat & Värme',
  'categories.cleaning': 'Robotar',
  'categories.garden': 'Trädgård',
  'categories.entertainment': 'Underhållning',
  'categories.all_desc': 'Komplett smart hem-upplevelse',
  'categories.security_desc': 'Skydda ditt hem',
  'categories.lighting_desc': 'Energisnål belysning',
  'categories.climate_desc': 'Temperaturstyrning',
  'categories.cleaning_desc': 'Automatisk rengöring',
  'categories.garden_desc': 'Smart trädgårdsskötsel',
  'categories.entertainment_desc': 'Högtalare & Hemmabio',
  
  // Service Categories
  'serviceCategories.el': 'El',
  'serviceCategories.vvs': 'VVS',
  'serviceCategories.snickeri': 'Snickeri',
  'serviceCategories.montering': 'Montering',
  'serviceCategories.tradgard': 'Trädgård',
  'serviceCategories.stadning': 'Städning',
  'serviceCategories.markarbeten': 'Markarbeten',
  'serviceCategories.tekniska-installationer': 'Tekniska installationer',
  'serviceCategories.flytt': 'Flytt',
  
  // Filter UI
  'filter.search_placeholder': 'Sök efter tjänst, t.ex. "dimmer", "IKEA", "diskmaskin"',
  'filter.all_services': 'Alla tjänster',
  'filter.all_prices': 'Alla priser',
  'filter.hourly_rate': 'Timpris',
  'filter.fixed_price': 'Fast pris',
  'filter.request_quote': 'Begär offert',
  'filter.all_locations': 'Alla platser',
  'filter.indoor': 'Inomhus',
  'filter.outdoor': 'Utomhus',
  'filter.clear': 'Rensa',
  'filter.specialty_areas': 'Specialområden:',
  'filter.searching': 'Sökning:',
  'filter.services_found': 'tjänster funna',
  'filter.no_services_rot_rut': 'Inga tjänster är berättigade till',
  'filter.with_current_filters': 'med dina nuvarande filter.',
  'filter.show_all_services': 'Visa alla tjänster',
  
  // Price display
  'price.saves_with_rot': 'Sparar',
  'price.saves_with_rut': 'Sparar',
  'price.with_rot_discount': 'med ROT-avdrag',
  'price.with_rut_discount': 'med RUT-avdrag',
  'price.show_rot_prices': 'Visa priser med ROT-avdrag (50% rabatt)',
  'filter.clear_other_filters': 'Rensa övriga filter',
  'filter.no_services_general': 'Inga tjänster matchade dina sökkriterier',
  'filter.clear_filters_try_again': 'Rensa filter och försök igen',
  
  // Service texts that need translation
  'service_text.quote_for': 'Offertförfrågan för',
  'service_text.booking_for': 'Bokning för',
  'service_text.started': 'påbörjad!',
  'service_text.sent': 'skickad!',
  
  // Individual service translations - EL
  'service.el-1.title': 'Byta vägguttag',
  'service.el-1.description': 'Byte av vägguttag till nyare modeller. Antal väljs vid bokning',
  'service.el-2.title': 'Byta strömbrytare och dimmer',
  'service.el-2.description': 'Installation av nya strömbrytare och dimrar. Antal väljs vid bokning',
  'service.el-3.title': 'Installera takarmatur/pendel',
  'service.el-3.description': 'Montering av takarmaturer och pendellampor. Antal väljs vid bokning',
  'service.el-4.title': 'Installera spotlights',
  'service.el-4.description': 'Installation av spotlights i tak. Antal väljs vid bokning (typiskt 0,5-1h per 4-6 st)',
  'service.el-5.title': 'Utebelysning',
  'service.el-5.description': 'Installation av fasad- och trädgårdsbelysning. Typ väljs vid bokning',
  'service.el-6.title': 'Installera jordfelsbrytare',
  'service.el-6.description': 'Installation av jordfelsbrytare för säkerhet',
  'service.el-7.title': 'Felsökning el',
  'service.el-7.description': 'Diagnostik och felsökning av elinstallationer (typiskt 1-2 h)',
  'service.el-8.title': 'Dra fram ny elpunkt',
  'service.el-8.description': 'Installation av ny elpunkt. Rum väljs vid bokning',
  'service.el-9.title': 'Montera TV-väggfäste & kabelkanal',
  'service.el-9.description': 'Montering av TV-fäste med kabelhantering',
  'service.el-10.title': 'Ny el till köksö',
  'service.el-10.description': 'Elinstallation för köksö med uttag',
  'service.el-11.title': 'Ny elgrupp',
  'service.el-11.description': 'Installation av ny elgrupp i centralen',
  
  // Individual service translations - VVS
  'service.vvs-1.title': 'Byta blandare',
  'service.vvs-1.description': 'Byte av blandare. Rum/typ väljs vid bokning',
  'service.vvs-2.title': 'Byta toalettstol',
  'service.vvs-2.description': 'Byte av toalettstol med installation',
  'service.vvs-3.title': 'Byta vattenlås & avloppssats',
  'service.vvs-3.description': 'Byte av vattenlås och avloppssats',
  'service.vvs-4.title': 'Montera diskmaskin',
  'service.vvs-4.description': 'Installation och anslutning av diskmaskin',
  'service.vvs-5.title': 'Montera tvättmaskin',
  'service.vvs-5.description': 'Installation och anslutning av tvättmaskin',
  'service.vvs-6.title': 'Installera duschblandare',
  'service.vvs-6.description': 'Installation av ny duschblandare',
  'service.vvs-7.title': 'Installera takdusch',
  'service.vvs-7.description': 'Installation av takdusch med rör',
  'service.vvs-8.title': 'Byta radiator',
  'service.vvs-8.description': 'Byte av radiator med anslutningar',
  'service.vvs-9.title': 'Byta termostatventil',
  'service.vvs-9.description': 'Byte av termostatventil på radiator',
  'service.vvs-10.title': 'Tätta rörkopplingar',
  'service.vvs-10.description': 'Täta läckande rörkopplingar',
  'service.vvs-11.title': 'Åtgärda dropp',
  'service.vvs-11.description': 'Reparera droppande kranar',
  'service.vvs-12.title': 'Golvbrunnsbyte',
  'service.vvs-12.description': 'Byte av golvbrunn med anslutningar',
  'service.vvs-13.title': 'Badrumsrenovering',
  'service.vvs-13.description': 'Komplett badrumsrenovering',
  
  // Individual service translations - SNICKERI
  'service.snickeri-1.title': 'Platsbyggd garderob',
  'service.snickeri-1.description': 'Tillverkning av platsbyggd garderob. Storlek väljs vid bokning',
  'service.snickeri-2.title': 'Köksluckor & bänkskivor',
  'service.snickeri-2.description': 'Byte av köksluckor och installation av bänkskivor',
  'service.snickeri-3.title': 'Inredning & hyllor',
  'service.snickeri-3.description': 'Tillverkning av specialanpassad inredning och hyllsystem',
  'service.snickeri-4.title': 'Dörrmontage',
  'service.snickeri-4.description': 'Montering av innerdörrar med karmar och handtag',
  'service.snickeri-5.title': 'Lister & finish',
  'service.snickeri-5.description': 'Installation av golv-, tak- och dörrfoder',
  
  // Individual service translations - MONTERING
  'service.montering-1.title': 'IKEA-möbler',
  'service.montering-1.description': 'Montering av alla typer av IKEA-möbler',
  'service.montering-2.title': 'TV-väggfäste',
  'service.montering-2.description': 'Säker montering av TV på vägg',
  'service.montering-3.title': 'Tavlor och speglar',
  'service.montering-3.description': 'Upphängning av tavlor, speglar och konst',
  'service.montering-4.title': 'Vitvaror (kyl, frys, ugn)',
  'service.montering-4.description': 'Installation och anslutning av vitvaror',
  
  // Individual service translations - TRADGARD
  'service.tradgard-1.title': 'Gräsklippning',
  'service.tradgard-1.description': 'Regelbunden gräsklippning och kanttrimning',
  'service.tradgard-2.title': 'Häckklippning',
  'service.tradgard-2.description': 'Beskärning av häckar och buskar',
  'service.tradgard-3.title': 'Ogräsrensning',
  'service.tradgard-3.description': 'Borttagning av ogräs från rabatter och gångar',
  'service.tradgard-4.title': 'Plantering och anläggning',
  'service.tradgard-4.description': 'Plantering av växter och anläggning av rabatter',
  'service.tradgard-5.title': 'Lövkrattning',
  'service.tradgard-5.description': 'Rensning av löv från gräsmatta och rabatter',
  'service.tradgard-6.title': 'Snöskottning/sandning',
  'service.tradgard-6.description': 'Snöröjning och halkbekämpning vid uppfart och gångar',
  
  // Individual service translations - STADNING
  'service.stadning-1.title': 'Hemstäd regelbundet',
  'service.stadning-1.description': 'Regelbunden städning av hemmet',
  'service.stadning-2.title': 'Flyttstäd',
  'service.stadning-2.description': 'Grundlig städning vid flytt',
  'service.stadning-3.title': 'Byggstäd',
  'service.stadning-3.description': 'Städning efter renovering och byggarbeten',
  'service.stadning-4.title': 'Fönsterputs',
  'service.stadning-4.description': 'Professionell fönsterputsning in- och utvändigt',
  'service.stadning-5.title': 'Djuprengöring kök/badrum',
  'service.stadning-5.description': 'Grundlig rengöring av kök eller badrum',
  'service.stadning-6.title': 'Kontorsstäd (B2B)',
  'service.stadning-6.description': 'Städning av kontorslokaler - företagskund',
  
  // Individual service translations - MARKARBETEN
  'service.markarbeten-1.title': 'Schaktning',
  'service.markarbeten-1.description': 'Grävning och schaktarbeten för grund och ledningar',
  'service.markarbeten-2.title': 'Dränering',
  'service.markarbeten-2.description': 'Installation av dräneringssystem',
  'service.markarbeten-3.title': 'Plattläggning',
  'service.markarbeten-3.description': 'Läggning av plattor och stenbeläggning',
  'service.markarbeten-4.title': 'Murverk',
  'service.markarbeten-4.description': 'Murarbeten och stensättning',
  
  // Individual service translations - TEKNISKA INSTALLATIONER
  'service.tekniska-1.title': 'Nätverk & IT',
  'service.tekniska-1.description': 'Installation av nätverk och IT-infrastruktur',
  'service.tekniska-2.title': 'Larmsystem',
  'service.tekniska-2.description': 'Installation av säkerhetslarm och övervakningssystem',
  'service.tekniska-3.title': 'Ljud & Bild',
  'service.tekniska-3.description': 'Installation av hemmabio och ljudsystem',
  
  // Individual service translations - FLYTT
  'service.flytt-1.title': 'Bärhjälp',
  'service.flytt-1.description': 'Hjälp med tunga lyft och transport',
  'service.flytt-2.title': 'Packning',
  'service.flytt-2.description': 'Professionell packning av dina tillhörigheter',
  'service.flytt-3.title': 'Flyttransport',
  'service.flytt-3.description': 'Transport av möbler och tillhörigheter',
  'service.flytt-4.title': 'Tömning till återvinning',
  'service.flytt-4.description': 'Tömning och transport till återvinning',
  'service.flytt-5.title': 'Ned/upp-montering av möbler',
  'service.flytt-5.description': 'Demontering och montering av möbler vid flytt',
  
  // Project visualization texts
  'project.eco_performance': 'Detta projekt har hög miljöprestanda tack vare energieffektiva material och metoder.',
  'project.ai_results': 'AI-genererade resultat',
  'project.environmental_impact': 'Miljöpåverkan analys',
  'project.rot_rut_optimization': 'ROT/RUT optimering',
  
  // Pages
  'pages.about.title': 'Om Fixco',
  'pages.about.subtitle': 'Din partner för professionella hantverk och byggnadsrjänster i Uppsala och Stockholm.',
  'pages.about.history_title': 'Vår historia',
  'pages.about.history_text': 'Fixco grundades med en enkel vision: att göra kvalitativa hemtjänster tillgängliga, enkla och prisvärda för alla. Våra erfarna hantverkare har arbetat med att leverantera högsta kvalité sedan starten, och erfarenheten vi skapat i byggnads- och renoveringsbranschen i regionen.',
  'pages.about.customers': 'Nöjda kunder',
  'pages.about.days_start': 'Vi startar på < 5 dagar',
  'pages.about.years_exp': '5 år',
  'pages.references.title': 'Referenser',
  
  // Service Detail Page
  'serviceDetail.notFound': 'Tjänsten hittades inte',
  'serviceDetail.backToServices': 'Tillbaka till tjänster',
  'serviceDetail.requestQuote': 'Begär offert',
  'serviceDetail.callUs': 'Ring 08-123 456 78',
  'serviceDetail.differentServices': 'Olika tjänster',
  'serviceDetail.projectStart': 'Projektstart',
  'serviceDetail.guaranteed': 'Garanterat',
  'serviceDetail.customerSatisfaction': 'kundnöjdhet',
  'serviceDetail.allOurServices': 'Alla våra',
  'serviceDetail.specializedServices': 'specialiserade tjänster med transparent prissättning.',
  'serviceDetail.allPricesInclude': 'Alla priser inkluderar moms och kan kombineras med ROT/RUT-avdrag för 50% rabatt.',
  'serviceDetail.availableIn': 'Tillgängligt i Uppsala & Stockholm',
  'serviceDetail.previous': 'Föregående',
  'serviceDetail.next': 'Nästa',
  'serviceDetail.customersAlsoBook': 'Kunder bokar även',
  'serviceDetail.relatedServices': 'Relaterade tjänster som ofta kombineras med',
  'serviceDetail.relatedService': 'Relaterad tjänst',
  'serviceDetail.readyToStart': 'Redo att komma igång med ditt',
  'serviceDetail.contactToday': 'Kontakta oss idag för en kostnadsfri konsultation. Vi hjälper dig från idé till färdigt resultat.',
  'serviceDetail.requestFreeQuote': 'Begär kostnadsfri offert',
  'serviceDetail.quickStart': 'Snabb start',
  'serviceDetail.canStartWithin': 'Vi kan påbörja ditt projekt inom 24-48 timmar',
  'serviceDetail.secureGuarantee': 'Trygg garanti',
  'serviceDetail.yearsGuarantee': '2 års garanti på alla utförda arbeten',
  'serviceDetail.rotRutHandling': 'ROT/RUT-hantering',
  'serviceDetail.weHandleAll': 'Vi sköter alla avdrag och administration',
  
  // Contact Page Extended  
  'pages.contact.bookVisit': 'Boka hembesök',

  // Contact Page
  'pages.contact.title': 'Kontakta oss',
  'pages.contact.subtitle': 'Få en kostnadsfri offert inom 24 timmar. Vi arbetar i Uppsala & Stockholms län (nationellt vid större projekt).',
  'pages.contact.quickResponse': 'Snabb respons',
  'pages.contact.quickResponseDesc': 'Svar inom 2 timmar',
  'pages.contact.freeQuote': 'Kostnadsfri offert',
  'pages.contact.freeQuoteDesc': 'Inga dolda kostnader',
  'pages.contact.localService': 'Lokal service',
  'pages.contact.localServiceDesc': 'Uppsala & Stockholm',
  'pages.contact.requestQuote': 'Begär offert',
  'pages.contact.formDescription': 'Fyll i formuläret så återkommer vi inom 24 timmar med en kostnadsfri och detaljerad offert.',
  'pages.contact.name': 'Namn',
  'pages.contact.phone': 'Telefon',
  'pages.contact.email': 'E-post',
  'pages.contact.address': 'Adress för projektet',
  'pages.contact.serviceType': 'Typ av tjänst',
  'pages.contact.selectService': 'Välj tjänst',
  'pages.contact.projectDescription': 'Beskrivning av projekt',
  'pages.contact.projectPlaceholder': 'Beskriv ditt projekt så detaljerat som möjligt. Vilka arbeten behöver utföras? Ungefär vilken tidsram? Finns det speciella önskemål?',
  'pages.contact.sendRequest': 'Skicka förfrågan',
  'pages.contact.sending': 'Skickar...',
  'pages.contact.consent': 'Genom att skicka formuläret godkänner du att vi kontaktar dig angående din förfrågan.',
  'pages.contact.contactInfo': 'Kontaktinformation',
  'pages.contact.telephone': 'Telefon',
  'pages.contact.callNow': 'Ring nu för akuta ärenden',
  'pages.contact.emailContact': 'E-post',
  'pages.contact.responseTime': 'Svar inom 2 timmar',
  'pages.contact.operatingArea': 'Verksamhetsområde',
  'pages.contact.areaDesc': 'Nationellt vid större projekt',
  'pages.contact.openingHours': 'Öppettider',
  'pages.contact.mondayFriday': 'Måndag - Fredag',
  'pages.contact.saturday': 'Lördag',
  'pages.contact.sunday': 'Söndag',
  'pages.contact.closed': 'Stängt',
  'pages.contact.emergencyService': 'Akutservice:',
  'pages.contact.emergencyDesc': 'Ring för akuta läckage och elfärder',
  'pages.contact.whyChoose': 'Varför välja Fixco?',
  'pages.contact.startIn24h': 'Start inom 24 timmar',
  'pages.contact.rotDeduction': 'ROT-avdrag - endast 480 kr/h',
  'pages.contact.guaranteedQuality': 'Garanterad kvalitet',
  'pages.contact.freeQuotes': 'Kostnadsfria offerter',
  'pages.contact.fieldsMissing': 'Fält saknas',
  'pages.contact.fillAllFields': 'Vänligen fyll i alla obligatoriska fält.',
  'pages.contact.thankYou': 'Tack för din förfrågan!',
  'pages.contact.responseIn24h': 'Vi återkommer inom 24 timmar med en kostnadsfri offert.',
  'pages.contact.somethingWrong': 'Något gick fel',
  'pages.contact.tryAgain': 'Vänligen försök igen eller ring oss direkt.',

  // FAQ Page
  'pages.faq.title': 'Vanliga frågor',
  'pages.faq.subtitle': 'Här hittar du svar på de vanligaste frågorna om våra tjänster, priser och arbetssätt.',
  'pages.faq.askQuestion': 'Ställ en fråga',
  'pages.faq.callUs': 'Ring oss: 08-123 456 78',
  'pages.faq.rotPrices': 'ROT-avdrag & Priser',
  'pages.faq.bookingTime': 'Bokning & Tidsramar',
  'pages.faq.qualityGuarantee': 'Kvalitet & Garanti',
  'pages.faq.practicalQuestions': 'Praktiska frågor',
  'pages.faq.noAnswer': 'Hittar du inte svar på din fråga?',
  'pages.faq.contactUs': 'Kontakta oss så hjälper vi dig gärna med dina frågor och funderingar.',
  'pages.faq.sendMessage': 'Skicka meddelande',

  // About Page Extended
  'pages.about.values': 'Våra värderingar',
  'pages.about.speed': 'Snabbhet',
  'pages.about.speedDesc': 'Vi starterar projekt inom 24 timmar och levererar alltid i tid. Ditt hem är viktigt och vi respekterar din tid.',
  'pages.about.quality': 'Kvalitet',
  'pages.about.qualityDesc': 'Alla våra hantverkare är certifierade och vi använder endast material av högsta kvalitet. Vi ger garanti på alla våra arbeten.',
  'pages.about.transparency': 'Transparens',
  'pages.about.transparencyDesc': 'Inga dolda kostnader, tydliga offerter och öppen kommunikation genom hela projektet. Du vet alltid vad du betalar för.',
  'pages.about.coverageArea': 'Vårt verksamhetsområde',
  'pages.about.coverageDesc': 'Vi täcker hela Uppsala kommun och Stockholms län med våra tjänster. Våra erfarna hantverkare kan vara hos dig inom kort för både akuta ärenden och planerade projekt.',
  'pages.about.readyToStart': 'Redo att komma igång?',
  'pages.about.contactToday': 'Kontakta oss idag för en kostnadsfri konsultation och offert. Vi är här för att hjälpa dig förverkliga dina projekt.',

  // Privacy Page
  'pages.privacy.title': 'Integritetspolicy',
  'pages.privacy.description': 'Vi värnar om din integritet. Denna sida är en placeholder och kommer att uppdateras med komplett policytext.',

  // Terms Page
  'pages.terms.title': 'Användarvillkor',
  'pages.terms.description': 'Här beskriver vi de villkor som gäller för användning av våra tjänster. Denna sida är en placeholder och kan uppdateras med fullständigt juridiskt innehåll senare.',

  // ROT Info Page
  'pages.rot.title': 'ROT-avdrag',
  'pages.rot.subtitle': 'Spara 50% på arbetskostnaden med ROT-avdraget. Vi hjälper dig genom hela processen så du får maximal avdrag utan krångel.',
  'pages.rot.bookVisit': 'Boka hembesök',
  'pages.rot.whatIs': 'Vad är ROT-avdrag?',
  'pages.rot.whatDesc': 'ROT-avdrag är ett skatteavdrag som ger dig 50% rabatt på arbetskostnaden för reparation, om- och tillbyggnad samt underhållsarbeten i din bostad.',
  'pages.rot.examples': 'Exempel på besparingar',
  'pages.rot.howWorks': 'Så enkelt fungerar det',
  'pages.rot.whatQualifies': 'Vad kvalificerar för ROT?',
  'pages.rot.readyToSave': 'Redo att spara 50% på ditt projekt?'
};