import type { CopyKey } from './keys';

export const sv: Record<CopyKey, string> = {
  // Navigation
  'nav.home': 'Hem',
  'nav.services': 'Tjänster', 
  'nav.smartHome': 'Smart Hem',
  'nav.references': 'Referenser',
  'nav.about': 'Om oss',
  'nav.contact': 'Kontakt',
  'nav.myFixco': 'Mitt Fixco',
  'nav.adminPanel': 'Adminpanel',
  
  // Trust chips
  'chips.f_skatt': 'F-skatt',
  'chips.insured': 'Försäkrade',
  'chips.start_lt_5': 'Start inom < 5 dagar',
  'chips.fixed_price': 'Fast pris',
  'chips.rot_50': 'ROT-avdrag 50%',
  'chips.rut_50': 'RUT-avdrag 50%',
  'chips.transparent': 'Transparent pris',
  'chips.free_quote': 'Kostnadsfri offert',
  'chips.we_handle_rot': 'Vi sköter ROT',
  'chips.happy_customers': '2000+ nöjda kunder',
  'chips.fast_support': 'Snabb support',
  'chips.certified': 'Certifierade',
  'chips.warranty': 'Garanti',
  'chips.eco_friendly': 'Miljövänligt',
  'chips.quick_response': 'Snabb respons',
  'chips.quality_work': 'Kvalitetsarbete',
  'chips.more': 'fler',
  
  // Buttons & CTAs
  'cta.book_now': 'Boka nu',
  'cta.request_quote': 'Begär offert',
  'cta.call_us': 'Ring oss',
  'cta.login': 'Logga in',
  'cta.get_quote': 'Få offert',
  'cta.see_all': 'Se alla →',
  'cta.book_direct': 'Boka direkt',
  'cta.book_installation': 'Boka Installation',
  'cta.free_consultation': 'Kostnadsfri konsultation',
  
  // Services
  'services.title': 'Våra tjänster',
  'services.subtitle': 'Från små reparationer till stora byggnationer – vi har expertisen och erfarenheten för att leverera professionella lösningar inom alla områden.',
  'services.rot_benefit': 'Utnyttja ROT-avdraget och spara 50%.',
  'services.choose_category': 'Välj kategori',
  'services.category_description': 'Hitta rätt tjänst för ditt hem snabbt och enkelt. Vi erbjuder allt från små reparationer till stora renoveringsprojekt.',
  'services.all_services': 'Alla tjänster',
  'services.all_services_description': 'Sök, filtrera och jämför våra tjänster snabbt och enkelt. Allt du behöver är synligt direkt - inga gömda menyer.',
  'services.visualize_project': 'Visualisera ditt projekt',
  'services.visualize_description': 'Se hur ditt hem kan se ut efter renovering med våra avancerade verktyg.',
  'services.ai_assistant': 'AI Projektassistent',
  'services.ai_description': 'Få personliga rekommendationer för att optimera ditt hem med AI-analys, ROT-avdrag och miljötänk.',
  'services.rot_section_title': 'ROT-avdraget – Spara 50% på arbetskostnaden',
  'services.rot_what_title': 'Vad är ROT-avdrag?',
  'services.rot_what_description': 'ROT-avdrag ger dig 50% rabatt på arbetskostnaden för reparation, om- och tillbyggnad samt underhållsarbeten i din bostad. Avdraget görs direkt från din skatt.',
  'services.rot_we_handle_title': 'Vi sköter allt',
  'services.rot_we_handle_description': 'Fixco hanterar alla ROT-ansökningar åt dig. Du behöver bara godkänna arbetet, resten ordnar vi. Enkelt och bekvämt.',
  'services.request_quote_rot': 'Begär offert med ROT-avdrag',
  'services.count': 'tjänster',
  'services.ordinary_price': 'Ordinarie pris:',
  'services.with_rot': 'Med ROT-avdrag:',
  'services.savings': 'Sparar',
  'services.energy_efficient': 'Energieffektiv lösning',
  'services.eco_materials': 'Miljövänliga material', 
  'services.ai_optimized': 'AI-optimerad',
  'services.rot_eligible': 'ROT-berättigad',
  'services.eco_score': 'Eco Score',
  'services.preview': 'Förhandsvisning',
  'services.show_3d': 'Visa i 3D',
  'services.incl_install': 'Inkl. installation & setup',
  
  // Smart Home
  'smartHome.title': 'Smart Hemautomation',
  'smartHome.subtitle': 'Styr och optimera ditt hem med AI och IoT-teknik',
  'smartHome.energy_reduction': 'Energiförbrukning',
  'smartHome.connected_devices': 'Anslutna enheter',
  'smartHome.automation': 'Automatisering',
  'smartHome.savings': 'Besparingar',
  'smartHome.products_title': 'Smart Hem - Verkliga Produkter',
  'smartHome.products_subtitle': 'Vi installerar endast beprövade, marknadsledande smart hem-produkter från världens största tillverkare. Alla produkter kommer med fullständig garanti och professionell installation.',
  'smartHome.all_products': 'Alla Smart Hem-Produkter',
  'smartHome.loading': 'Laddar produkter...',
  'smartHome.no_products': 'Inga produkter hittades',
  'smartHome.market_leaders': 'Marknadsledande Märken',
  'smartHome.full_warranty': 'Fullständig Garanti',
  'smartHome.professional_install': 'Professionell Installation',
  'smartHome.ai_optimized': 'AI-Optimerad',
  'smartHome.choose_category': 'Välj Produktkategori',
  'smartHome.main_features': 'Huvudfunktioner:',
  'smartHome.smart_features': 'Smarta Funktioner:',
  'smartHome.installation_setup': 'Inkl. installation & setup',
  'smartHome.years_warranty': '2 års fullgaranti',
  
  // Categories
  'categories.all': 'Alla Produkter',
  'categories.security': 'Säkerhet & Lås',
  'categories.lighting': 'Smart Belysning',
  'categories.climate': 'Klimat & Värme',
  'categories.cleaning': 'Robotar',
  'categories.garden': 'Trädgård',
  'categories.entertainment': 'Underhållning',
  'categories.all_desc': 'Komplett smart hem-upplevelse',
  'categories.security_desc': 'Skydda ditt hem',
  'categories.lighting_desc': 'Energisnål belysning',
  'categories.climate_desc': 'Temperaturstyrning',
  'categories.cleaning_desc': 'Automatisk rengöring',
  'categories.garden_desc': 'Smart trädgårdsskötsel',
  'categories.entertainment_desc': 'Högtalare & Hemmabio',
  
  // Service Categories
  'serviceCategories.el': 'El',
  'serviceCategories.vvs': 'VVS',
  'serviceCategories.snickeri': 'Snickeri',
  'serviceCategories.montering': 'Montering',
  'serviceCategories.tradgard': 'Trädgård',
  'serviceCategories.stadning': 'Städning',
  'serviceCategories.markarbeten': 'Markarbeten',
  'serviceCategories.tekniska': 'Tekniska installationer',
  'serviceCategories.flytt': 'Flytt',
  
  // Pages
  'pages.about.title': 'Om Fixco',
  'pages.about.subtitle': 'Din partner för professionella hantverk och byggnadsrjänster i Uppsala och Stockholm.',
  'pages.about.history_title': 'Vår historia',
  'pages.about.history_text': 'Fixco grundades med en enkel vision: att göra kvalitativa hemtjänster tillgängliga, enkla och prisvärda för alla. Våra erfarna hantverkare har arbetat med att leverantera högsta kvalité sedan starten, och erfarenheten vi skapat i byggnads- och renoveringsbranschen i regionen.',
  'pages.about.customers': 'Nöjda kunder',
  'pages.about.days_start': 'Vi startar på < 5 dagar',
  'pages.about.years_exp': '5 år',
  'pages.contact.title': 'Kontakta Fixco',
  'pages.references.title': 'Referenser',
  
  // Breadcrumbs
  'breadcrumbs.home': 'Hem',
  'breadcrumbs.services': 'Tjänster'
};