import type { CopyKey } from './keys';

export const sv: Record<CopyKey, string> = {
  // Navigation
  'nav.home': 'Hem',
  'nav.services': 'Tjänster',
  'nav.smartHome': 'Smart Hem',
  'nav.references': 'Referenser',
  'nav.about': 'Om oss',
  'nav.contact': 'Kontakt',
  'nav.myFixco': 'Mitt Fixco',
  'nav.adminPanel': 'Adminpanel',
  
  // Common
  'common.phone': '+46 79 335 02 28',
  'common.services': 'Tjänster',
  
  // Trust chips
  'chips.f_skatt': 'F-skatt',
  'chips.insured': 'Försäkrade',
  'chips.start_lt_5': 'Start inom < 5 dagar',
  'chips.fixed_price': 'Fast pris',
  'chips.rot_50': 'ROT-avdrag 50%',
  'chips.rut_50': 'RUT-avdrag 50%',
  'chips.transparent': 'Transparent pris',
  'chips.free_quote': 'Kostnadsfri offert',
  'chips.we_handle_rot': 'Vi sköter ROT',
  'chips.happy_customers': '2000+ nöjda kunder',
  'chips.fast_support': 'Snabb support',
  'chips.certified': 'Certifierade',
  'chips.warranty': 'Garanti',
  'chips.eco_friendly': 'Miljövänligt',
  'chips.quick_response': 'Snabb respons',
  'chips.quality_work': 'Kvalitetsarbete',
  'chips.more': 'fler',
  
  // Buttons & CTAs
  'cta.book_now': 'Boka nu',
  'cta.request_quote': 'Begär offert',
  'cta.call_us': 'Ring oss',
  'cta.login': 'Logga in',
  'cta.get_quote': 'Få offert',
  'cta.see_all': 'Se alla →',
  'cta.book_direct': 'Boka direkt',
  'cta.book_installation': 'Boka Installation',
  'cta.free_consultation': 'Kostnadsfri konsultation',
  
  // Services
  'services.title': 'Våra tjänster',
  'services.subtitle': 'Från små reparationer till stora byggnationer – vi har expertisen och erfarenheten för att leverera professionella lösningar inom alla områden.',
  'services.rot_benefit': 'Utnyttja ROT- & RUT-avdraget och spara 50%.',
  'services.choose_category': 'Välj kategori',
  'services.category_description': 'Hitta rätt tjänst för ditt hem snabbt och enkelt. Vi erbjuder allt från små reparationer till stora renoveringsprojekt.',
  'services.all_services': 'Alla tjänster',
  'services.all_services_description': 'Sök, filtrera och jämför våra tjänster snabbt och enkelt. Allt du behöver är synligt direkt - inga gömda menyer.',
  'services.visualize_project': 'Visualisera ditt projekt',
  'services.visualize_description': 'Se hur ditt hem kan se ut efter renovering med våra avancerade verktyg.',
  'services.ai_assistant': 'AI Projektassistent',
  'services.ai_description': 'Få personliga rekommendationer för att optimera ditt hem med AI-analys, ROT-avdrag och miljötänk.',
  'services.rot_section_title': 'ROT-avdraget – Spara 50% på arbetskostnaden',
  'services.rot_what_title': 'Vad är ROT-avdrag?',
  'services.rot_what_description': 'ROT-avdrag ger dig 50% rabatt på arbetskostnaden för reparation, om- och tillbyggnad samt underhållsarbeten i din bostad. Avdraget görs direkt från din skatt.',
  'services.rot_we_handle_title': 'Vi sköter allt',
  'services.rot_we_handle_description': 'Fixco hanterar alla ROT-ansökningar åt dig. Du behöver bara godkänna arbetet, resten ordnar vi. Enkelt och bekvämt.',
  'services.request_quote_rot': 'Begär offert med ROT-avdrag',
  'services.count': 'tjänster',
  'services.ordinary_price': 'Ordinarie pris:',
  'services.with_rot': 'Med ROT-avdrag:',
  'services.savings': 'Sparar',
  'services.energy_efficient': 'Energieffektiv lösning',
  'services.eco_materials': 'Miljövänliga material', 
  'services.ai_optimized': 'AI-optimerad',
  'services.rot_eligible': 'ROT-berättigad',
  'services.eco_score': 'Eco Score',
  'services.preview': 'Förhandsvisning',
  'services.show_3d': 'Visa i 3D',
  'services.incl_install': 'Inkl. installation & setup',
  'services.quote_after_inspection': 'Prisuppgift efter besiktning',
  
  // Smart Home
  'smartHome.title': 'Smart Hemautomation',
  'smartHome.subtitle': 'Styr och optimera ditt hem med AI och IoT-teknik',
  'smartHome.energy_reduction': 'Energiförbrukning',
  'smartHome.connected_devices': 'Anslutna enheter',
  'smartHome.automation': 'Automatisering',
  'smartHome.savings': 'Besparingar',
  'smartHome.products_title': 'Smart Hem - Verkliga Produkter',
  'smartHome.products_subtitle': 'Vi installerar endast beprövade, marknadsledande smart hem-produkter från världens största tillverkare. Alla produkter kommer med fullständig garanti och professionell installation.',
  'smartHome.all_products': 'Alla Smart Hem-Produkter',
  'smartHome.loading': 'Laddar produkter...',
  'smartHome.no_products': 'Inga produkter hittades',
  'smartHome.market_leaders': 'Marknadsledande Märken',
  'smartHome.full_warranty': 'Fullständig Garanti',
  'smartHome.professional_install': 'Professionell Installation',
  'smartHome.ai_optimized': 'AI-Optimerad',
  'smartHome.choose_category': 'Välj Produktkategori',
  'smartHome.main_features': 'Huvudfunktioner:',
  'smartHome.smart_features': 'Smarta Funktioner:',
  'smartHome.installation_setup': 'Inkl. installation & setup',
  'smartHome.years_warranty': '2 års fullgaranti',
  'smartHome.contact_for_info': 'Kontakta oss för installation och mer information!',
  'smartHome.market_leaders_desc': 'Endast #1 märken globalt',
  'smartHome.professional_desc': 'Certifierade installatörer',
  'smartHome.ai_desc': 'Intelligent automatisering',
  'smartHome.compatibility_title': 'Kompatibilitet',
  'smartHome.compatibility_desc': 'Alla produkter fungerar tillsammans och har säkra protokoll som Zigbee 3.0 och WiFi 6.',
  'smartHome.easy_support_title': 'Enkel Support',
  'smartHome.easy_support_desc': 'Vi är certifierade installatörer för alla märken. En kontakt för alla dina smart hem-behov.',
  'smartHome.future_proof_title': 'Framtidssäkert',
  'smartHome.future_proof_desc': 'Alla produkter får regelbundna uppdateringar med nya funktioner. Din investering växer över tid.',
  'smartHome.ready_for_install_title': 'Redo för Professionell Smart Hem-Installation?',
  'smartHome.ready_for_install_desc': 'Boka en kostnadsfri hemkonsultation idag. Vi kommer hem till dig med produkterna, visar hur de fungerar och ger dig en exakt offert på installationen.',
  'smartHome.book_installation': 'Boka Installation',
  'smartHome.why_these_brands': 'Varför Vi Valt Dessa Märken',
  'smartHome.market_leaders_title': 'Marknadsledare',
  'smartHome.market_leaders_long_desc': 'Alla märken är #1 eller #2 i sina kategorier globalt. Beprövad teknik med miljontals installationer.',
  
  // Projects / References
  'projects.latest_title': 'Se våra senaste projekt',
  'projects.latest_subtitle': 'Från drömkök till lyxiga badrum - våra senaste projekt visar kvaliteten och kreativiteten som våra kunder får. Alla med garanterat ROT-avdrag.',
  'projects.satisfied_customers': '100% nöjda kunder',
  'projects.on_time_budget': 'I tid & budget',
  'projects.all_stockholm': 'Hela Stockholm',
  'projects.completed': 'Färdigställt',
  'projects.cta_title': 'Vill du se ditt hem här?',
  'projects.cta_subtitle': 'Vi skapar drömhemmet du alltid velat ha. Från första skissen till färdigt resultat - vi finns med dig hela vägen. Alla projekt inkluderar ROT-avdrag för maximal besparing.',
  'projects.request_quote': 'Begär kostnadsfri offert',
  'projects.see_more': 'Se fler projekt',
  'projects.new_project': 'Nytt projekt',
  
  // FAQ Teaser
  'faq.no_answer_title': 'Hittar du inte svar på din fråga?',
  'faq.contact_response': 'Kontakta oss direkt så svarar vi inom 30 minuter',
  'faq.call_us_with_phone': 'Ring oss: +46 79 335 02 28',
  'faq.tell_project': 'Berätta om ditt projekt',
  
  // Categories
  'categories.all': 'Alla Produkter',
  'categories.security': 'Säkerhet & Lås',
  'categories.lighting': 'Smart Belysning',
  'categories.climate': 'Klimat & Värme',
  'categories.cleaning': 'Robotar',
  'categories.garden': 'Trädgård',
  'categories.entertainment': 'Underhållning',
  'categories.all_desc': 'Komplett smart hem-upplevelse',
  'categories.security_desc': 'Skydda ditt hem',
  'categories.lighting_desc': 'Energisnål belysning',
  'categories.climate_desc': 'Temperaturstyrning',
  'categories.cleaning_desc': 'Automatisk rengöring',
  'categories.garden_desc': 'Smart trädgårdsskötsel',
  'categories.entertainment_desc': 'Högtalare & Hemmabio',
  
  // Service Categories (keep both versions for compatibility)
  'serviceCategories.el': 'El',
  'serviceCategories.vvs': 'VVS',
  'serviceCategories.snickeri': 'Snickeri',
  'serviceCategories.malning': 'Målare',
  'serviceCategories.malare': 'Målare',
  'serviceCategories.malare.title': 'Målare',
  'serviceCategories.malare.description': 'Professionell målning inomhus och utomhus',
  'serviceCategories.montering': 'Montering',
  'serviceCategories.tradgard': 'Trädgård',
  'serviceCategories.stadning': 'Städning',
  'serviceCategories.markarbeten': 'Markarbeten',
  'serviceCategories.tekniska-installationer': 'Tekniska installationer',
  'serviceCategories.flytt': 'Flytt',

  // Service Categories Extended
  'serviceCategories.el.title': 'El',
  'serviceCategories.el.description': 'Installation, reparation och underhåll av el',
  'serviceCategories.vvs.title': 'VVS', 
  'serviceCategories.vvs.description': 'Rör, vatten och avlopp',
  'serviceCategories.snickeri.title': 'Snickeri',
  'serviceCategories.snickeri.description': 'Specialanpassade lösningar i trä',
  'serviceCategories.malning.title': 'Målning',
  'serviceCategories.malning.description': 'Professionell målning inomhus och utomhus',
  'serviceCategories.montering.title': 'Montering',
  'serviceCategories.montering.description': 'Möbler och vitvaror',
  'serviceCategories.tradgard.title': 'Trädgård',
  'serviceCategories.tradgard.description': 'Skötsel och anläggning',
  'serviceCategories.stadning.title': 'Städning',
  'serviceCategories.stadning.description': 'Hemservice och rengöring',
  'serviceCategories.markarbeten.title': 'Markarbeten',
  'serviceCategories.markarbeten.description': 'Grävning och anläggning',
  'serviceCategories.tekniska-installationer.title': 'Tekniska installationer',
  'serviceCategories.tekniska-installationer.description': 'Nätverk, larm och IT-support',
  'serviceCategories.flytt.title': 'Flytt',
  'serviceCategories.flytt.description': 'Transport och bärhjälp',
  
  // Filter UI
  'filter.search_placeholder': 'Sök efter tjänst, t.ex. "dimmer", "IKEA", "diskmaskin"',
  'filter.all_services': 'Alla tjänster',
  'filter.all_prices': 'Alla priser',
  'filter.hourly_rate': 'Timpris',
  'filter.fixed_price': 'Fast pris',
  'filter.request_quote': 'Begär offert',
  'filter.all_locations': 'Alla platser',
  'filter.indoor': 'Inomhus',
  'filter.outdoor': 'Utomhus',
  'filter.clear': 'Rensa',
  'filter.specialty_areas': 'Specialområden:',
  'filter.searching': 'Sökning:',
  'filter.services_found': 'tjänster funna',
  'filter.no_services_rot_rut': 'Inga tjänster är berättigade till',
  'filter.with_current_filters': 'med dina nuvarande filter.',
  'filter.show_all_services': 'Visa alla tjänster',
  
  // Price display
  'price.saves_with_rot': 'Sparar',
  'price.saves_with_rut': 'Sparar',
  'price.with_rot_discount': 'med ROT-avdrag',
  'price.with_rut_discount': 'med RUT-avdrag',
  'price.show_rot_prices': 'Visa priser med ROT-avdrag (50% rabatt)',
  'filter.clear_other_filters': 'Rensa övriga filter',
  'filter.no_services_general': 'Inga tjänster matchade dina sökkriterier',
  'filter.clear_filters_try_again': 'Rensa filter och försök igen',
  
  // Service texts that need translation
  'service_text.quote_for': 'Offertförfrågan för',
  'service_text.booking_for': 'Bokning för',
  'service_text.started': 'påbörjad!',
  'service_text.sent': 'skickad!',
  
  // Individual service translations - EL
  'service.el-1.title': 'Byta vägguttag',
  'service.el-1.description': 'Byte av vägguttag till nyare modeller. Antal väljs vid bokning',
  'service.el-2.title': 'Byta strömbrytare och dimmer',
  'service.el-2.description': 'Installation av nya strömbrytare och dimrar. Antal väljs vid bokning',
  'service.el-3.title': 'Installera takarmatur/pendel',
  'service.el-3.description': 'Montering av takarmaturer och pendellampor. Antal väljs vid bokning',
  'service.el-4.title': 'Installera spotlights',
  'service.el-4.description': 'Installation av spotlights i tak. Antal väljs vid bokning (typiskt 0,5-1h per 4-6 st)',
  'service.el-5.title': 'Utebelysning',
  'service.el-5.description': 'Installation av fasad- och trädgårdsbelysning. Typ väljs vid bokning',
  'service.el-6.title': 'Installera jordfelsbrytare',
  'service.el-6.description': 'Installation av jordfelsbrytare för säkerhet',
  'service.el-7.title': 'Felsökning el',
  'service.el-7.description': 'Diagnostik och felsökning av elinstallationer (typiskt 1-2 h)',
  'service.el-8.title': 'Dra fram ny elpunkt',
  'service.el-8.description': 'Installation av ny elpunkt. Rum väljs vid bokning',
  'service.el-9.title': 'Montera TV-väggfäste & kabelkanal',
  'service.el-9.description': 'Montering av TV-fäste med kabelhantering',
  'service.el-10.title': 'Ny el till köksö',
  'service.el-10.description': 'Elinstallation för köksö med uttag',
  'service.el-11.title': 'Ny elgrupp',
  'service.el-11.description': 'Installation av ny elgrupp i centralen',
  
  // Individual service translations - VVS
  'service.vvs-1.title': 'Byta blandare',
  'service.vvs-1.description': 'Byte av blandare. Rum/typ väljs vid bokning',
  'service.vvs-2.title': 'Byta toalettstol',
  'service.vvs-2.description': 'Byte av toalettstol med installation',
  'service.vvs-3.title': 'Byta vattenlås & avloppssats',
  'service.vvs-3.description': 'Byte av vattenlås och avloppssats',
  'service.vvs-4.title': 'Montera diskmaskin',
  'service.vvs-4.description': 'Installation och anslutning av diskmaskin',
  'service.vvs-5.title': 'Montera tvättmaskin',
  'service.vvs-5.description': 'Installation och anslutning av tvättmaskin',
  'service.vvs-6.title': 'Installera duschblandare',
  'service.vvs-6.description': 'Installation av ny duschblandare',
  'service.vvs-7.title': 'Installera takdusch',
  'service.vvs-7.description': 'Installation av takdusch med rör',
  'service.vvs-8.title': 'Byta radiator',
  'service.vvs-8.description': 'Byte av radiator med anslutningar',
  'service.vvs-9.title': 'Byta termostatventil',
  'service.vvs-9.description': 'Byte av termostatventil på radiator',
  'service.vvs-10.title': 'Tätta rörkopplingar',
  'service.vvs-10.description': 'Täta läckande rörkopplingar',
  'service.vvs-11.title': 'Åtgärda dropp',
  'service.vvs-11.description': 'Reparera droppande kranar',
  'service.vvs-12.title': 'Golvbrunnsbyte',
  'service.vvs-12.description': 'Byte av golvbrunn med anslutningar',
  'service.vvs-13.title': 'Badrumsrenovering',
  'service.vvs-13.description': 'Komplett badrumsrenovering',
  
  // Individual service translations - SNICKERI
  'service.snickeri-1.title': 'Platsbyggd garderob',
  'service.snickeri-1.description': 'Tillverkning av platsbyggd garderob. Storlek väljs vid bokning',
  'service.snickeri-2.title': 'Köksluckor & bänkskivor',
  'service.snickeri-2.description': 'Byte av köksluckor och installation av bänkskivor',
  'service.snickeri-3.title': 'Inredning & hyllor',
  'service.snickeri-3.description': 'Tillverkning av specialanpassad inredning och hyllsystem',
  'service.snickeri-4.title': 'Dörrmontage',
  'service.snickeri-4.description': 'Montering av innerdörrar med karmar och handtag',
  'service.snickeri-5.title': 'Lister & finish',
  'service.snickeri-5.description': 'Installation av golv-, tak- och dörrfoder',
  
  // Individual service translations - MONTERING
  'service.montering-1.title': 'IKEA-möbler',
  'service.montering-1.description': 'Montering av alla typer av IKEA-möbler',
  'service.montering-2.title': 'TV-väggfäste',
  'service.montering-2.description': 'Säker montering av TV på vägg',
  'service.montering-3.title': 'Tavlor och speglar',
  'service.montering-3.description': 'Upphängning av tavlor, speglar och konst',
  'service.montering-4.title': 'Vitvaror (kyl, frys, ugn)',
  'service.montering-4.description': 'Installation och anslutning av vitvaror',
  
  // Individual service translations - TRADGARD
  'service.tradgard-1.title': 'Gräsklippning',
  'service.tradgard-1.description': 'Regelbunden gräsklippning och kanttrimning',
  'service.tradgard-2.title': 'Häckklippning',
  'service.tradgard-2.description': 'Beskärning av häckar och buskar',
  'service.tradgard-3.title': 'Ogräsrensning',
  'service.tradgard-3.description': 'Borttagning av ogräs från rabatter och gångar',
  'service.tradgard-4.title': 'Plantering och anläggning',
  'service.tradgard-4.description': 'Plantering av växter och anläggning av rabatter',
  'service.tradgard-5.title': 'Lövkrattning',
  'service.tradgard-5.description': 'Rensning av löv från gräsmatta och rabatter',
  'service.tradgard-6.title': 'Snöskottning/sandning',
  'service.tradgard-6.description': 'Snöröjning och halkbekämpning vid uppfart och gångar',
  
  // Individual service translations - STADNING
  'service.stadning-1.title': 'Hemstäd regelbundet',
  'service.stadning-1.description': 'Regelbunden städning av hemmet',
  'service.stadning-2.title': 'Flyttstäd',
  'service.stadning-2.description': 'Grundlig städning vid flytt',
  'service.stadning-3.title': 'Byggstäd',
  'service.stadning-3.description': 'Städning efter renovering och byggarbeten',
  'service.stadning-4.title': 'Fönsterputs',
  'service.stadning-4.description': 'Professionell fönsterputsning in- och utvändigt',
  'service.stadning-5.title': 'Djuprengöring kök/badrum',
  'service.stadning-5.description': 'Grundlig rengöring av kök eller badrum',
  'service.stadning-6.title': 'Kontorsstäd (B2B)',
  'service.stadning-6.description': 'Städning av kontorslokaler - företagskund',
  
  // Individual service translations - MARKARBETEN
  'service.markarbeten-1.title': 'Schaktning',
  'service.markarbeten-1.description': 'Grävning och schaktarbeten för grund och ledningar',
  'service.markarbeten-2.title': 'Dränering',
  'service.markarbeten-2.description': 'Installation av dräneringssystem',
  'service.markarbeten-3.title': 'Plattläggning',
  'service.markarbeten-3.description': 'Läggning av plattor och stenbeläggning',
  'service.markarbeten-4.title': 'Murverk',
  'service.markarbeten-4.description': 'Murarbeten och stensättning',
  
  // Individual service translations - TEKNISKA INSTALLATIONER
  'service.tekniska-1.title': 'Nätverk & IT',
  'service.tekniska-1.description': 'Installation av nätverk och IT-infrastruktur',
  'service.tekniska-2.title': 'Larmsystem',
  'service.tekniska-2.description': 'Installation av säkerhetslarm och övervakningssystem',
  'service.tekniska-3.title': 'Ljud & Bild',
  'service.tekniska-3.description': 'Installation av hemmabio och ljudsystem',
  
  // Individual service translations - FLYTT
  'service.flytt-1.title': 'Bärhjälp',
  'service.flytt-1.description': 'Hjälp med tunga lyft och transport',
  'service.flytt-2.title': 'Packning',
  'service.flytt-2.description': 'Professionell packning av dina tillhörigheter',
  'service.flytt-3.title': 'Flyttransport',
  'service.flytt-3.description': 'Transport av möbler och tillhörigheter',
  'service.flytt-4.title': 'Tömning till återvinning',
  'service.flytt-4.description': 'Tömning och transport till återvinning',
  'service.flytt-5.title': 'Ned/upp-montering av möbler',
  'service.flytt-5.description': 'Demontering och montering av möbler vid flytt',
  
  // Project visualization texts
  'project.eco_performance': 'Detta projekt har hög miljöprestanda tack vare energieffektiva material och metoder.',
  'project.ai_results': 'AI-genererade resultat',
  'project.environmental_impact': 'Miljöpåverkan analys',
  'project.rot_rut_optimization': 'ROT/RUT optimering',
  
  // Pages
  'pages.about.title': 'Om Fixco',
  'pages.about.history_title': 'Vår historia',
  'pages.about.history_text': 'Fixco grundades med en enkel vision: att göra kvalitativa hemtjänster tillgängliga, enkla och prisvärda för alla. Våra erfarna hantverkare har arbetat med att leverantera högsta kvalité sedan starten, och erfarenheten vi skapat i byggnads- och renoveringsbranschen i regionen.',
  'pages.about.customers': 'Nöjda kunder',
  'pages.about.days_start': 'Vi startar på < 5 dagar',
  'pages.about.years_exp': '5 år',
  'pages.references.title': 'Referenser',
  'pages.references.description': 'Se exempel på våra senaste projekt och läs vad våra nöjda kunder säger om oss.',
  'pages.references.newProject': 'Nytt projekt',
  'pages.references.stats.completed': 'Slutförda projekt',
  'pages.references.stats.avgRating': 'Medelbetyg',
  'pages.references.stats.savings': 'ROT/RUT-besparingar',
  'pages.references.stats.satisfaction': 'Nöjda kunder',
  'pages.references.heading': 'Våra Referensprojekt',
  'pages.references.gridDescription': 'Här är alla våra projekt som visar bredden och kvaliteten i vårt arbete.',
  'pages.references.loading': 'Laddar projekt...',
  'pages.references.viewAllImages': 'Se alla bilder',
  'pages.references.rotSaving': 'ROT-besparing: ',
  'pages.references.rutSaving': 'RUT-besparing: ',
  'pages.references.duration': 'Projekttid:',
  'pages.references.client': 'Klient:',
  'pages.references.deleteConfirm': 'Är du säker på att du vill radera detta projekt?',
  'pages.servicesOverview.title': 'Våra',
  'pages.servicesOverview.titleHighlight': 'tjänster',
  'pages.servicesOverview.subtitle': 'Från små reparationer till stora byggnationer – vi har expertisen och erfarenheten för att leverera professionella lösningar inom alla områden',
  'pages.servicesOverview.seeMore': 'Se mer →',
  'pages.servicesOverview.cantFind': 'Hittar du inte den tjänst du söker? Kontakta oss för mer information.',
  'pages.servicesOverview.seeAll': 'Se alla tjänster',
  'pages.auth.loginFailed': 'Inloggning misslyckades',
  'pages.auth.unknownError': 'Okänt fel uppstod',
  'pages.auth.tryAgain': 'Försök igen',
  'pages.auth.backHome': 'Tillbaka till startsidan',
  'pages.auth.needHelp': 'Behöver du hjälp?',
  'pages.auth.contactUs': 'Kontakta oss',
  
  // Service Detail Page
  'serviceDetail.notFound': 'Tjänsten hittades inte',
  'serviceDetail.backToServices': 'Tillbaka till tjänster',
  'serviceDetail.requestQuote': 'Begär offert',
  'serviceDetail.callUs': 'Ring +46 79 335 02 28',
  'serviceDetail.differentServices': 'Olika tjänster',
  'serviceDetail.projectStart': 'Projektstart',
  'serviceDetail.guaranteed': 'Garanterat',
  'serviceDetail.customerSatisfaction': 'kundnöjdhet',
  'serviceDetail.allOurServices': 'Alla våra',
  'serviceDetail.specializedServices': 'specialiserade tjänster med transparent prissättning.',
  'serviceDetail.allPricesInclude': 'Alla priser inkluderar moms och kan kombineras med ROT/RUT-avdrag för 50% rabatt.',
  'serviceDetail.availableIn': 'Tillgängligt i Uppsala & Stockholm',
  'serviceDetail.previous': 'Föregående',
  'serviceDetail.next': 'Nästa',
  'serviceDetail.customersAlsoBook': 'Kunder bokar även',
  'serviceDetail.relatedServices': 'Relaterade tjänster som ofta kombineras med',
  'serviceDetail.relatedService': 'Relaterad tjänst',
  'serviceDetail.readyToStart': 'Redo att komma igång med ditt',
  'serviceDetail.contactToday': 'Kontakta oss idag för en kostnadsfri konsultation. Vi hjälper dig från idé till färdigt resultat.',
  'serviceDetail.requestFreeQuote': 'Begär kostnadsfri offert',
  'serviceDetail.quickStart': 'Snabb start',
  'serviceDetail.canStartWithin': 'Vi kan påbörja ditt projekt inom 24-48 timmar',
  'serviceDetail.secureGuarantee': 'Trygg garanti',
  'serviceDetail.yearsGuarantee': '2 års garanti på alla utförda arbeten',
  'serviceDetail.rotRutHandling': 'ROT/RUT-hantering',
  'serviceDetail.weHandleAll': 'Vi sköter alla avdrag och administration',
  'serviceDetail.days': 'dagar',
  'serviceDetail.discount': 'rabatt', 
  'serviceDetail.taxAndInsurance': 'skatt & försäkring',
  'serviceDetail.startWithinDays': 'Start inom < 5 dagar',
  
  // Contact Page Extended  
  'pages.contact.bookVisit': 'Boka hembesök',

  // Contact Page
  'pages.contact.title': 'Kontakta oss',
  'pages.contact.subtitle': 'Få en kostnadsfri offert inom 24 timmar. Vi arbetar i Uppsala & Stockholms län (nationellt vid större projekt).',
  'pages.contact.quickResponse': 'Snabb respons',
  'pages.contact.quickResponseDesc': 'Svar inom 2 timmar',
  'pages.contact.freeQuote': 'Kostnadsfri offert',
  'pages.contact.freeQuoteDesc': 'Inga dolda kostnader',
  'pages.contact.localService': 'Lokal service',
  'pages.contact.localServiceDesc': 'Uppsala & Stockholm',
  'pages.contact.requestQuote': 'Begär offert',
  'pages.contact.formDescription': 'Fyll i formuläret så återkommer vi inom 24 timmar med en kostnadsfri och detaljerad offert.',
  'pages.contact.name': 'Namn',
  'pages.contact.phone': 'Telefon',
  'pages.contact.email': 'E-post',
  'pages.contact.address': 'Adress för projektet',
  'pages.contact.serviceType': 'Typ av tjänst',
  'pages.contact.selectService': 'Välj tjänst',
  'pages.contact.projectDescription': 'Beskrivning av projekt',
  'pages.contact.projectPlaceholder': 'Beskriv ditt projekt så detaljerat som möjligt. Vilka arbeten behöver utföras? Ungefär vilken tidsram? Finns det speciella önskemål?',
  'pages.contact.sendRequest': 'Skicka förfrågan',
  'pages.contact.sending': 'Skickar...',
  'pages.contact.consent': 'Genom att skicka formuläret godkänner du att vi kontaktar dig angående din förfrågan.',
  'pages.contact.contactInfo': 'Kontaktinformation',
  'pages.contact.telephone': 'Telefon',
  'pages.contact.callNow': 'Ring nu för akuta ärenden',
  'pages.contact.emailContact': 'E-post',
  'pages.contact.responseTime': 'Svar inom 2 timmar',
  'pages.contact.operatingArea': 'Verksamhetsområde',
  'pages.contact.areaDesc': 'Nationellt vid större projekt',
  'pages.contact.openingHours': 'Öppettider',
  'pages.contact.mondayFriday': 'Måndag - Fredag',
  'pages.contact.saturday': 'Lördag',
  'pages.contact.sunday': 'Söndag',
  'pages.contact.closed': 'Stängt',
  'pages.contact.emergencyService': 'Akutservice:',
  'pages.contact.emergencyDesc': 'Ring för akuta läckage och elfärder',
  'pages.contact.whyChoose': 'Varför välja Fixco?',
  'pages.contact.startIn24h': 'Start inom 24 timmar',
  'pages.contact.rotDeduction': 'ROT-avdrag - endast 480 kr/h',
  'pages.contact.guaranteedQuality': 'Garanterad kvalitet',
  'pages.contact.freeQuotes': 'Kostnadsfria offerter',
  'pages.contact.fieldsMissing': 'Fält saknas',
  'pages.contact.fillAllFields': 'Vänligen fyll i alla obligatoriska fält.',
  'pages.contact.thankYou': 'Tack för din förfrågan!',
  'pages.contact.responseIn24h': 'Vi återkommer inom 24 timmar med en kostnadsfri offert.',
  'pages.contact.somethingWrong': 'Något gick fel',
  'pages.contact.tryAgain': 'Vänligen försök igen eller ring oss direkt.',

  // FAQ Page
  'pages.faq.title': 'Vanliga frågor',
  'pages.faq.subtitle': 'Här hittar du svar på de vanligaste frågorna om våra tjänster, priser och arbetssätt.',
  'pages.faq.askQuestion': 'Ställ en fråga',
  'pages.faq.callUs': 'Ring oss: +46 79 335 02 28',
  'pages.faq.rotPrices': 'ROT-avdrag & Priser',
  'pages.faq.bookingTime': 'Bokning & Tidsramar',
  'pages.faq.qualityGuarantee': 'Kvalitet & Garanti',
  'pages.faq.practicalQuestions': 'Praktiska frågor',
  'pages.faq.noAnswer': 'Hittar du inte svar på din fråga?',
  'pages.faq.contactUs': 'Kontakta oss så hjälper vi dig gärna med dina frågor och funderingar.',
  'pages.faq.sendMessage': 'Skicka meddelande',

  // About Page Extended
  'pages.about.values': 'Våra värderingar',
  'pages.about.subtitle': 'Från en idé om bättre hantverk till Uppsala & Stockholms ledande fastighetspartner',
  'pages.about.founded_vision': 'Fixco grundades av tre hantverkare som var trötta på dålig kommunikation och opålitliga entreprenörer i branschen. Visionen var enkel: skapa ett företag där kvalitet, transparens och respekt för kundens tid står i centrum.',
  'pages.about.growth_story': 'Efter två år växte vi från 3 till 12 anställda. Vi började specialisera oss på både små akuta reparationer och större renoveringsprojekt.',
  'pages.about.pandemic_adapt': 'Under pandemin såg vi en ökning av efterfrågan på hemarbeten. Vi anpassade oss snabbt och investerade i digital projektstyrning för att kunna arbeta säkert och effektivt.',
  'pages.about.today_team': 'Idag är vi ett team på 25+ certifierade hantverkare med bred kompetens inom el, VVS, bygg, målning och smart hem-lösningar.',
  'pages.about.current_status': 'Vi fortsätter växa och har nu hjälpt över 2000 familjer, BRF:er och företag i Uppsala och Stockholm med deras fastighetsprojekt.',
  'pages.about.what_we_offer_title': 'Vad vi erbjuder',
  'pages.about.for_private_title': 'För Privatpersoner',
  'pages.about.for_private_desc': 'Vi hjälper husägare och lägenhetsbor med allt från akuta reparationer till planerade renoveringar. Oavsett om det är ett sprucket rör, ny belysning eller totalrenovering av badrummet.',
  'pages.about.for_brf_title': 'För BRF & Fastighetsägare',
  'pages.about.for_brf_desc': 'Vi arbetar med bostadsrättsföreningar och fastighetsägare för underhåll, stambyten, fasadrenovering och löpande service. Vi förstår vikten av god kommunikation med styrelse och boende.',
  'pages.about.for_business_title': 'För Företag',
  'pages.about.for_business_desc': 'Vi hjälper företag med kontorslokaler, butiker och verksamhetslokaler. Från akuta reparationer till planerade om- och tillbyggnationer.',
  'pages.about.our_team_title': 'Människorna bakom Fixco',
  'pages.about.team_description': 'Vårt team består av certifierade elektriker, rörmokare, byggare, målare och projektledare. Alla med minst 10 års erfarenhet inom sina respektive områden. Vi tror på kontinuerlig utbildning och håller oss uppdaterade med de senaste teknologierna och metoderna - allt från traditionellt hantverk till modern smart hem-integration. Vi är stolta över att vara ett inkluderande företag där varje teammedlem respekteras för sin expertis och sitt engagemang.',
  'pages.about.quality_value': 'Kvalitet',
  'pages.about.quality_value_desc': 'Vi står för vårt arbete. Varje projekt, stort som litet, utförs med samma omsorg och precision. Vi tar inte genvägar.',
  'pages.about.transparency_value': 'Transparens',
  'pages.about.transparency_value_desc': 'Inga dolda kostnader, inga överraskningar. Vi kommunicerar öppet om tid, kostnad och eventuella utmaningar under projektets gång.',
  'pages.about.respect_value': 'Respekt',
  'pages.about.respect_value_desc': 'Vi respekterar ditt hem, din tid och ditt förtroende. Vi städar alltid efter oss och kommer när vi säger att vi ska komma.',
  'pages.about.where_we_operate': 'Där vi verkar',
  'pages.about.coverage_simple': 'Vi är baserade i Uppsala och arbetar främst i Uppsala län och Stockholms län. För större projekt tar vi också uppdrag i hela Mellansverige.',
  'pages.about.want_to_know_more': 'Vill du veta mer?',
  'pages.about.contact_us_desc': 'Har du frågor om oss eller vill diskutera ett projekt? Kontakta oss så berättar vi mer.',
  'pages.about.contact_us_button': 'Kontakta oss',
  'pages.about.see_services_button': 'Se våra tjänster',

  // Privacy Page
  'pages.privacy.title': 'Integritetspolicy',
  'pages.privacy.description': 'Vi värnar om din integritet. Denna sida är en placeholder och kommer att uppdateras med komplett policytext.',

  // Terms Page
  'pages.terms.title': 'Användarvillkor',
  'pages.terms.description': 'Här beskriver vi de villkor som gäller för användning av våra tjänster. Denna sida är en placeholder och kan uppdateras med fullständigt juridiskt innehåll senare.',

  // ROT Info Page
  'pages.rot.title': 'ROT-avdrag med Fixco',
  'pages.rot.subtitle': 'Spara 50% på arbetskostnaden med ROT-avdrag. Vi sköter allt pappersarbete åt dig.',
  'pages.rot.hero.title': 'Spara 50% med ROT-avdrag',
  'pages.rot.hero.subtitle': 'Vi hjälper dig få maximalt ROT-avdrag och sköter alla ansökningar åt dig. Helt enkelt.',
  'pages.rot.hero.bookVisit': 'Boka hembesök',
  'pages.rot.hero.phone': 'Ring: +46 79 335 02 28',
  'pages.rot.what.title': 'Vad är ROT-avdrag?',
  'pages.rot.what.description1': 'ROT-avdrag är ett skatteavdrag som ger dig 50% rabatt på arbetskostnaden för reparation, om- och tillbyggnad samt underhållsarbeten i din bostad.',
  'pages.rot.what.description2': 'Avdraget görs direkt från din skatt och du kan få maximalt 50 000 kr per person och år. För sambor blir det totalt 100 000 kr per hushåll.',
  'pages.rot.what.benefit1': '50% rabatt på arbetskostnaden',
  'pages.rot.what.benefit2': 'Max 50 000 kr per person och år',
  'pages.rot.what.benefit3': 'Gäller för permanentbostäder',
  'pages.rot.what.benefit4': 'Vi sköter alla ansökningar',
  'pages.rot.what.discount': '50% Rabatt',
  'pages.rot.what.discountDescription': 'Du betalar bara hälften av arbetskostnaden när du använder ROT-avdraget',
  'pages.rot.examples.title': 'Exempel på besparingar',
  'pages.rot.examples.service1': 'Köksblandare byte',
  'pages.rot.examples.service2': 'Toalettstol byte',
  'pages.rot.examples.service3': 'Köksrenovering',
  'pages.rot.examples.work1': '2 timmar arbete',
  'pages.rot.examples.work2': 'Fast pris',
  'pages.rot.examples.work3': '40 timmar arbete',
  'pages.rot.examples.savings': 'Du sparar:',
  'pages.rot.examples.price': 'Pris:',
  'pages.rot.examples.withRot': 'Med ROT-avdrag:',
  'pages.rot.process.title': 'Så enkelt fungerar det',
  'pages.rot.process.step1.title': 'Vi gör jobbet',
  'pages.rot.process.step1.description': 'Du bokar tjänsten och vi utför arbetet professionellt enligt offert.',
  'pages.rot.process.step2.title': 'Vi skickar in ansökan',
  'pages.rot.process.step2.description': 'Vi fyller i och skickar ROT-ansökan till Skatteverket åt dig. Inget krångel för dig.',
  'pages.rot.process.step3.title': 'Du betalar rabatterat pris',
  'pages.rot.process.step3.description': 'Du betalar bara 50% av arbetskostnaden direkt till oss. Resten får du tillbaka via skatten.',
  'pages.rot.qualifies.title': 'Vad kvalificerar för ROT?',
  'pages.rot.qualifies.yes.title': '✅ Kvalificerar för ROT',
  'pages.rot.qualifies.no.title': '❌ Kvalificerar INTE för ROT',
  'pages.rot.cta.title': 'Redo att spara 50% på ditt projekt?',
  'pages.rot.cta.description': 'Boka en kostnadsfri konsultation så hjälper vi dig få maximal ROT-avdrag.',
  'pages.rot.cta.bookNow': 'Boka hembesök nu',
  'pages.rot.cta.requestQuote': 'Begär offert',

  // RUT Info Page
  'pages.rut.title': 'RUT-avdrag med Fixco',
  'pages.rut.subtitle': 'Spara 50% på arbetskostnaden för hemservice med RUT-avdrag. Vi sköter allt pappersarbete åt dig.',
  'pages.rut.hero.title': 'Spara 50% med RUT-avdrag',
  'pages.rut.hero.subtitle': 'Vi hjälper dig få maximalt RUT-avdrag för hemservice och sköter alla ansökningar åt dig. Helt enkelt.',
  'pages.rut.hero.bookVisit': 'Boka hembesök',
  'pages.rut.hero.phone': 'Ring: +46 79 335 02 28',
  'pages.rut.what.title': 'Vad är RUT-avdrag?',
  'pages.rut.what.description1': 'RUT-avdrag är ett skatteavdrag som ger dig 50% rabatt på arbetskostnaden för rengöring, underhåll och tvätt i din bostad.',
  'pages.rut.what.description2': 'Avdraget görs direkt från din skatt och du kan få maximalt 50 000 kr per person och år. För sambor blir det totalt 100 000 kr per hushåll.',
  'pages.rut.what.benefit1': '50% rabatt på arbetskostnaden',
  'pages.rut.what.benefit2': 'Max 50 000 kr per person och år',
  'pages.rut.what.benefit3': 'Gäller för permanentbostäder',
  'pages.rut.what.benefit4': 'Vi sköter alla ansökningar',
  'pages.rut.what.discount': '50% Rabatt',
  'pages.rut.what.discountDescription': 'Du betalar bara hälften av arbetskostnaden när du använder RUT-avdraget',
  'pages.rut.examples.title': 'Exempel på besparingar',
  'pages.rut.examples.service1': 'Hemstäd',
  'pages.rut.examples.service2': 'Fönsterputs',
  'pages.rut.examples.service3': 'Byggstäd',
  'pages.rut.examples.work1': '4 timmar städning',
  'pages.rut.examples.work2': '2 timmar arbete',
  'pages.rut.examples.work3': '8 timmar arbete',
  'pages.rut.examples.savings': 'Du sparar:',
  'pages.rut.examples.price': 'Pris:',
  'pages.rut.examples.withRut': 'Med RUT-avdrag:',
  'pages.rut.process.title': 'Så enkelt fungerar det',
  'pages.rut.process.step1.title': 'Vi utför tjänsten',
  'pages.rut.process.step1.description': 'Du bokar hemservice och vi utför arbetet professionellt enligt överenskommelse.',
  'pages.rut.process.step2.title': 'Vi skickar in ansökan',
  'pages.rut.process.step2.description': 'Vi fyller i och skickar RUT-ansökan till Skatteverket åt dig. Inget krångel för dig.',
  'pages.rut.process.step3.title': 'Du betalar rabatterat pris',
  'pages.rut.process.step3.description': 'Du betalar bara 50% av arbetskostnaden direkt till oss. Resten får du tillbaka via skatten.',
  'pages.rut.qualifies.title': 'Vad kvalificerar för RUT?',
  'pages.rut.qualifies.yes.title': '✅ Kvalificerar för RUT',
  'pages.rut.qualifies.no.title': '❌ Kvalificerar INTE för RUT',
  'pages.rut.cta.title': 'Redo att spara 50% på hemservice?',
  'pages.rut.cta.description': 'Boka en kostnadsfri konsultation så hjälper vi dig få maximal RUT-avdrag.',
  'pages.rut.cta.bookNow': 'Boka hembesök nu',
  'pages.rut.cta.requestQuote': 'Begär offert',
  'home.comparison.title': 'Varför välja Fixco?',
  'home.comparison.subtitle': 'Transparent jämförelse som visar varför tusentals kunder väljer oss',
  'home.services.title': 'Våra huvudtjänster',
  'home.services.subtitle': 'Från små reparationer till stora projekt – vi hanterar allt professionellt',
  'home.services.viewAll': 'Se alla tjänster',
  'home.hero.title': 'Bygg- & fastighetstjänster för privat, BRF & företag',
  'home.hero.subtitle': 'Expertlösningar för alla fastighetsbehov – från el till målning. Fast pris. ROT/RUT garanterat. Gratis offert inom 24h.',
  'home.hero.primaryCta': 'Begär kostnadsfri offert',
  'home.finalCta.title': 'Redo att starta ditt projekt?',
  'home.finalCta.subtitle': 'Få en kostnadsfri offert inom 24 timmar och se varför tusentals kunder väljer Fixco',
  'home.finalCta.primaryButton': 'Boka nu - gratis offert',
  'home.finalCta.secondaryButton': 'Ring: +46 79 335 02 28',
  'services.el.title': 'El',
  'services.el.description': 'Uttag, belysning, laddbox',
  'services.vvs.title': 'VVS',
  'services.vvs.description': 'WC, handfat, duschvägg',
  'services.snickeri.title': 'Snickeri',
  'services.snickeri.description': 'Kök, garderober, lister',
  'services.montering.title': 'Montering',
  'services.montering.description': 'IKEA, vitvaror, TV-fästen',
  'services.tradgard.title': 'Trädgård',
  'services.tradgard.description': 'Gräs, häck, ogräs, snö',
  'services.stadning.title': 'Städning',
  'services.stadning.description': 'Hem, bygg, kontor, flytt',
  'services.flytt.title': 'Flytt',
  'services.flytt.description': 'Bärhjälp, lastning, packning',
  'services.tekniska.title': 'Tekniska installationer',
  'services.tekniska.description': 'Nätverk, larm, ljud & bild',
  'services.category.main': 'Huvudtjänst',
  'location.uppsala_stockholm': 'Uppsala & Stockholm',
  'location.national_large_projects': 'Nationellt vid större projekt',
  'timing.start_within_5_days': 'Start inom < 5 dagar',
  'timing.less_than_5_days': '< 5 dagar',
  'comparison.coverage_area': 'Område',
  'comparison.limited': 'Begränsat',
  'comparison.5_10_days': '5-10 dagar',
  'comparison.coverage_description': 'Full täckning i Uppsala & Stockholm, större projekt nationellt',
  'comparison.timing_description': 'Vi börjar inom 5 dagar vs konkurrenters veckolånga väntetider',
  'comparison.start_time': 'Starttid',
  'comparison.header': 'Jämförelse',
  'comparison.competitors': 'Konkurrenter',
  'trust.f_tax': 'F-skatt',
  'trust.f_tax_desc': 'Godkänd för ROT & RUT',
  'trust.insured': 'Försäkrade',
  'trust.insured_desc': 'Ansvarsförsäkring 10M kr',
  'trust.fast_start': 'Start inom < 5 dagar',
  'trust.fast_start_desc': 'Oftast inom 5 dagar',
  'trust.fixed_price': 'Fast pris',
  'trust.fixed_price_desc': 'Där det är möjligt',
  'trust.rating': '4.9/5 betyg',
  'trust.rating_desc': 'Över 500 recensioner',
  'trust.coverage': 'Uppsala & Stockholm',
  'trust.coverage_desc': 'Lokalt & nationellt',
  'hero.title_large': 'Stora',
  'hero.title_or': 'eller',
  'hero.title_small': 'små',
  'hero.title_projects': 'projekt –',
  'hero.subtitle': 'Snabbare, billigare och mer professionellt än våra konkurrenter.',
  'hero.fixco_handles': 'Fixco hanterar',
  'hero.everything': 'allt',
  'hero.cta_request_quote': 'Begär offert',
  'hero.cta_see_services': 'Se våra tjänster',
  'hero.trust_rot': 'ROT-avdrag:',
  'hero.trust_rot_desc': '50% rabatt',
  'hero.trust_coverage': 'Nationell täckning:',
  'hero.trust_coverage_desc': 'Hela Sverige',
  'hero.trust_start': 'Snabb start:',
  'hero.trust_start_desc': 'Inom < 5 dagar',
  'hero.trust_quality': 'Fixco Kvalitet',
  'hero.trust_quality_desc': 'Vårt löfte till dig',
  'hero.trust_price': 'Lägst pris (ROT)',
  'hero.trust_price_desc': '480 kr/h efter ROT-avdrag',
  'hero.trust_customers': '2000+ kunder',
  'hero.trust_customers_desc': 'Genomsnittligt betyg 4.9/5',
  'hero.trust_locations': 'Uppsala & Stockholm',
  'hero.trust_locations_desc': 'Nationellt vid större projekt',
  'comparison.price_title': 'Pris',
  'comparison.price_rot_desc': 'Med 50% ROT-avdrag blir våra priser marknadsledande',
  'comparison.price_no_rot_desc': 'Konkurrensdyktig timprissättning med transparent prismodell',
  
  // Additional comparison terms
  'comparison.customer_satisfaction': 'Kundnöjdhet',
  'comparison.customer_satisfaction_desc': 'Branschens högsta kundnöjdhet baserat på tusentals recensioner',
  'comparison.rut_handling': 'RUT-hantering',
  'comparison.rut_handling_fixco': 'Vi sköter allt',
  'comparison.rut_handling_competitor': 'Sköter också',
  'comparison.rut_handling_desc': 'Vi hanterar all RUT-administration för hushållsnära tjänster',
  'comparison.project_completion': 'Projekt klart i tid',
  'comparison.project_completion_desc': 'Nästan alla projekt levereras enligt överenskommen tidsplan',
  'comparison.wins_all': 'Fixco vinner',
  'comparison.market_leader': 'Marknadsledare inom alla områden',
  'comparison.start_time_label': 'Starttid',
  'comparison.satisfied_customers': 'Nöjda kunder',
  'comparison.support': 'Support',
  'comparison.request_quote': 'Begär offert',
  'comparison.see_all_services': 'Se alla våra tjänster',
  'comparison.days': 'dagar',
  'comparison.within_days': 'inom',
  
  // AI Page
  'ai.page_title': 'Fixco AI Concierge - Smarta hemtjänster med AI',
  'ai.page_subtitle': 'Chatta med Fixco AI, få visualiseringar på dina bilder, och få snabba offert-estimat med ROT-avdrag. Uppsala & Stockholm.',
  'ai.powered_by': 'Powered by AI',
  'ai.hero_title': 'Fixco AI Concierge',
  'ai.hero_subtitle': 'Din smarta assistent för hemrenoveringar. Få råd, visualiseringar och offerter direkt.',
  'ai.chat_title': 'Chatta med Fixco AI',
  'ai.chat_greeting': 'Hej! Jag är Fixco AI Concierge. Hur kan jag hjälpa dig idag? Jag kan svara på frågor om våra tjänster, hjälpa dig visualisera förändringar i ditt hem, eller ta fram en preliminär offert.',
  'ai.chat_error': 'Förlåt, något gick fel. Försök igen eller kontakta oss direkt på +46 79 335 02 28.',
  'ai.chat_placeholder': 'Skriv ditt meddelande...',
  'ai.chat_send': 'Skicka',
  'ai.image_title': 'Bild & Förslag',
  'ai.image_subtitle': 'Ladda upp en bild av ditt rum eller utrymme och beskriv vad du vill se',
  'ai.image_upload': 'Välj bild',
  'ai.image_choose': 'Välj bild',
  'ai.image_max_size': 'max 15 MB',
  'ai.image_instruction_placeholder': 'Ex: "Lägg akustikpanel i mörk ek på väggen bakom TV:n, vertikala ribbor"',
  'ai.image_generate': 'Generera efter-bild',
  'ai.image_generating': 'Genererar...',
  'ai.image_result': 'Resultat:',
  'ai.image_before': 'Före',
  'ai.image_after': 'Efter',
  'ai.image_download': 'Ladda ner',
  'ai.image_disclaimer': 'OBS: Visualisering är indikativ - färg och struktur kan avvika från verkligt material.',
  'ai.image_file_too_large': 'Filen är för stor',
  'ai.image_missing_info': 'Saknas information',
  'ai.image_missing_desc': 'Ladda upp en bild och beskriv önskad förändring',
  'ai.image_complete': 'Visualisering klar!',
  'ai.image_complete_desc': 'Din efter-bild har genererats',
  'ai.image_error': 'Fel vid bildbearbetning',
  'ai.quote_title': 'Offert',
  'ai.quote_subtitle': 'Beräkna preliminär offert med ROT-avdrag',
  'ai.quote_service': 'Tjänst',
  'ai.quote_choose_service': 'Välj tjänst',
  'ai.quote_quantity': 'Omfattning',
  'ai.quote_material': 'Material (kr)',
  'ai.quote_work': 'Arbete:',
  'ai.quote_subtotal': 'Delsumma:',
  'ai.quote_vat': 'Moms (25%):',
  'ai.quote_total_incl_vat': 'Totalt inkl. moms:',
  'ai.quote_rot_deduction': 'Indikativt ROT-avdrag (30% på arbete):',
  'ai.quote_after_rot': 'Efter ROT:',
  'ai.quote_create_pdf': 'Skapa PDF',
  'ai.quote_generating': 'Genererar...',
  'ai.quote_email_placeholder': 'E-postadress',
  'ai.quote_send': 'Skicka',
  'ai.quote_disclaimer': 'OBS: Detta är en preliminär beräkning. Slutligt pris kan variera beroende på projektets komplexitet. ROT-avdraget bedöms slutligt av Skatteverket.',
  'ai.quote_pdf_created': 'PDF skapad!',
  'ai.quote_pdf_desc': 'Öppnar offerten i nytt fönster',
  'ai.quote_sent': 'Offert skickad!',
  'ai.quote_sent_desc': 'PDF-offert skickad till',
  'ai.quote_missing_email': 'Saknas information',
  'ai.quote_fill_email': 'Fyll i e-postadress',
  'ai.quote_pdf_error': 'Fel vid PDF-generering',
  'ai.quote_pdf_error_desc': 'Försök igen eller kontakta support',
  'ai.quote_email_error': 'Fel vid e-postsändning',
  'ai.quote_email_error_desc': 'Försök igen eller kontakta support',
  'ai.feature1_title': 'Expertråd 24/7',
  'ai.feature1_desc': 'Få professionella råd om byggnation, renovering och inredning när du behöver det',
  'ai.feature2_title': 'AI-visualiseringar',
  'ai.feature2_desc': 'Se hur ditt hem kan se ut efter renoveringen - direkt på dina egna bilder',
  'ai.feature3_title': 'Snabba offerter',
  'ai.feature3_desc': 'Få preliminära offerter med ROT-beräkning på några sekunder',
  'ai.disclaimer_title': 'OBS:',
  'ai.disclaimer_text': 'Fixco AI är en assistent som ger preliminära råd och visualiseringar. Slutliga offerter och bedömningar görs alltid av våra professionella hantverkare. ROT-avdrag bedöms slutligt av Skatteverket.',
  
  // AI Lab page (now main AI page)
  'ailab.title': 'AI Lab',
  
  // Floating AI Widget
  'ai_widget.launcher': 'AI',
  'ai_widget.title': 'Fixco AI',
  'ai_widget.tab_chat': 'Chatta',
  'ai_widget.tab_image': 'Bild & Förslag',
  'ai_widget.close': 'Stäng',
  'ai_widget.chat_placeholder': 'Skriv din fråga…',
  'ai_widget.send': 'Skicka',
  'ai_widget.open_full': 'Öppna full AI',
  'ai_widget.create_offer': 'Skapa offert',
  'ai_widget.greeting': 'Hej! Ladda upp en bild i fliken Bild & Förslag eller ställ en fråga här.',
  'ai_widget.image_instruction_placeholder': 'Ex: Lägg akustikpanel i mörk ek på väggen bakom TV:n',
  'ai_widget.generate': 'Generera efter-bild',
  'ai_widget.error': 'Något gick fel. Försök igen.',
  'ai_widget.upload_file': 'Välj bild',
  'ailab.subtitle': 'Visualisera ditt projekt och få prisuppskattning direkt',
  'ailab.upload_title': 'Ladda upp bild',
  'ailab.upload_subtitle': 'Börja med att ladda upp en bild av rummet eller ytan',
  'ailab.drag_drop': 'Dra och släpp bild här',
  'ailab.or_click': 'eller klicka för att välja',
  'ailab.action_cards_title': 'Välj vad du vill göra',
  'ailab.action_acoustic': 'Akustikpanel',
  'ailab.action_deck': 'Bygg altan',
  'ailab.action_floor': 'Byt golv',
  'ailab.action_bookshelf': 'Platsbyggd bokhylla',
  'ailab.action_wardrobe': 'Garderober',
  'ailab.action_led': 'LED-belysning',
  'ailab.custom_instruction': 'Egen instruktion',
  'ailab.custom_placeholder': 'Beskriv vad du vill ha gjort...',
  'ailab.visualize_btn': 'Visualisera',
  'ailab.visualizing': 'Skapar visualisering...',
  'ailab.before_title': 'Före',
  'ailab.after_title': 'Efter',
  'ailab.variants_title': 'Välj stil',
  'ailab.estimate_title': 'Prisuppskattning',
  'ailab.estimate_subtitle': 'Preliminär kostnad inklusive moms',
  'ailab.labor': 'Arbetskostnad',
  'ailab.material': 'Material',
  'ailab.subtotal': 'Delsumma',
  'ailab.vat': 'Moms (25%)',
  'ailab.total_incl_vat': 'Totalt inkl. moms',
  'ailab.rot_deduction': 'ROT-avdrag (30% på arbete)',
  'ailab.rot_info': 'Indikativt ROT-avdrag',
  'ailab.final_price': 'Att betala efter ROT',
  'ailab.contact_title': 'Spara ditt projekt',
  'ailab.contact_subtitle': 'Fyll i dina uppgifter för att få offerten',
  'ailab.name_label': 'Namn',
  'ailab.email_label': 'E-post',
  'ailab.phone_label': 'Telefon',
  'ailab.address_label': 'Adress',
  'ailab.create_pdf': 'Skapa PDF-offert',
  'ailab.send_email': 'Skicka offert via e-post',
  'ailab.sending': 'Skickar...',
  'ailab.pdf_created': 'PDF skapad!',
  'ailab.email_sent': 'Offert skickad!',
  'ailab.lead_saved': 'Projekt sparat!',
  'ailab.error_upload': 'Kunde inte ladda upp bilden',
  'ailab.error_file_size': 'Filen är för stor (max 15 MB)',
  'ailab.error_file_type': 'Endast JPEG, PNG och WEBP stöds',
  'ailab.error_visualization': 'Kunde inte skapa visualisering',
  'ailab.error_missing_image': 'Ladda upp en bild först',
  'ailab.error_missing_contact': 'Fyll i kontaktuppgifter',
  'ailab.disclaimer': 'Priser är preliminära och baseras på uppskattningar. Exakt pris ges efter platsbesök.',
  'ailab.policy': 'ROT-avdraget är indikativt. Slutlig bedömning görs av Skatteverket.'
};