/**
 * Shared SEO data for generate-seo-inline.mjs
 * Service slug → display name (Swedish), area slug → display name, sv→en mapping
 */

// ─── Service slug → display name (Swedish) ───
export const SERVICES = {
  'snickare':'Snickare','elektriker':'Elektriker','vvs':'VVS','malare':'Målare',
  'tradgard':'Trädgård','stad':'Städ','markarbeten':'Markarbeten','montering':'Montering',
  'flytt':'Flytt','tekniska-installationer':'Tekniska installationer',
  'koksmontering':'Köksmontering','mobelmontering':'Möbelmontering',
  'badrumsrenovering':'Badrumsrenovering','koksrenovering':'Köksrenovering',
  'altanbygge':'Altanbygge','fasadmalning':'Fasadmålning','inomhusmalning':'Inomhusmålning',
  'golvlaggning':'Golvläggning','elinstallation':'Elinstallation','rivning':'Rivning',
  'totalrenovering':'Totalrenovering','renovering':'Renovering','hantverkare':'Hantverkare',
  'byggfirma':'Byggfirma','byggtjanster':'Byggtjänster','husrenovering':'Husrenovering',
  'villarenovering':'Villarenovering','lagenhetsrenovering':'Lägenhetsrenovering',
  'ombyggnad':'Ombyggnad','utbyggnad':'Utbyggnad','tillbyggnad':'Tillbyggnad',
  'fonsterbyte':'Fönsterbyte','dorrbyte':'Dörrbyte','fasadrenovering':'Fasadrenovering',
  'trapprenovering':'Trapprenovering','taklaggning':'Takläggning','takbyte':'Takbyte',
  'takrenovering':'Takrenovering','verandarenovering':'Verandarenovering',
  'entrerenoverning':'Entrérenoverning','vardagsrumsrenovering':'Vardagsrumsrenovering',
  'sovrumsrenovering':'Sovrumsrenovering','kontorsbygge':'Kontorsbygge',
  'bostadsanpassning':'Bostadsanpassning','platsbyggt':'Platsbyggt',
  'kok':'Kök','koksbyte':'Köksbyte','ikea-koksmontage':'IKEA-köksmontage',
  'koksinstallation':'Köksinstallation','koksdesign':'Köksdesign','nytt-kok':'Nytt kök',
  'koksluckor':'Köksluckor','bankskiva':'Bänkskiva','platsbyggt-kok':'Platsbyggt kök',
  'koksplanering':'Köksplanering','vitvaruinstallation-kok':'Vitvaruinstallation kök',
  'diskbanksbyte':'Diskbänksbyte','koksbelysning':'Köksbelysning','koksflakt':'Köksfläkt',
  'stankskydd':'Stänkskydd','badrum':'Badrum','badrumskakel':'Badrumskakel',
  'plattsattning':'Plattsättning','tatskikt':'Tätskikt','wc-renovering':'WC-renovering',
  'duschrum':'Duschrum','duschvagg':'Duschvägg','badrumsinredning':'Badrumsinredning',
  'tvattrum':'Tvättrum','badrumsgolv':'Badrumsgolv',
  'elarbeten':'Elarbeten','elreparation':'Elreparation','laddbox':'Laddbox',
  'laddboxinstallation':'Laddboxinstallation','sakringsbyte':'Säkringsbyte',
  'belysning':'Belysning','elcentral':'Elcentral','eljour':'Eljour',
  'lampmontering':'Lampmontering','spotlights':'Spotlights','elbesiktning':'Elbesiktning',
  'jordfelsbrytare':'Jordfelsbrytare',
  'vvs-arbeten':'VVS-arbeten','rorjour':'Rörjour','rorarbeten':'Rörarbeten',
  'varmepump':'Värmepump','vattenlas':'Vattenlås','avlopp':'Avlopp',
  'golvvarme':'Golvvärme','vattenbatteri':'Vattenbatteri','blandarbyte':'Blandarbyte',
  'radiatorbyte':'Radiatorbyte',
  'malning':'Målning','tapetsering':'Tapetsering','spackling':'Spackling',
  'lackering':'Lackering','fonstermalning':'Fönstermålning','takmalning':'Takmålning',
  'trappmalning':'Trappmålning','snickerimlaning':'Snickerimålning',
  'golvslipning':'Golvslipning','parkettlaggning':'Parkettläggning',
  'laminatgolv':'Laminatgolv','vinylgolv':'Vinylgolv','klinkergolv':'Klinkergolv',
  'epoxigolv':'Epoxigolv','golvbyte':'Golvbyte',
  'tradgardsanlaggning':'Trädgårdsanläggning','tradgardsskotsel':'Trädgårdsskötsel',
  'grasklippning':'Gräsklippning','hackklippning':'Häckklippning',
  'tradbeskaring':'Trädbeskärning','tradgardsdesign':'Trädgårdsdesign',
  'stenlaggning-tradgard':'Stenläggning trädgård','buskrojning':'Buskröjning',
  'dranering':'Dränering','schaktning':'Schaktning','plattlaggning':'Plattläggning',
  'stenlaggning':'Stenläggning','asfaltering':'Asfaltering','murverk':'Murverk',
  'uppfart':'Uppfart','garageuppfart':'Garageuppfart',
  'hemstad':'Hemstäd','flyttstad':'Flyttstäd','byggstad':'Byggstäd',
  'fonsterputs':'Fönsterputs','storstadning':'Storstädning','kontorsstad':'Kontorsstäd',
  'dodsbo':'Dödsbo','trappstad':'Trappstäd',
  'garderobsmontering':'Garderobsmontering','tv-montering':'TV-montering',
  'persiennmontering':'Persiennmontering','hyllmontering':'Hyllmontering',
  'ikeamontering':'IKEA-montering','dorrmontering':'Dörrmontering',
  'flytthjalp':'Flytthjälp','packhjalp':'Packhjälp','kontorsflytt':'Kontorsflytt',
  'magasinering':'Magasinering','pianoflytt':'Pianoflytt',
  'larm':'Larm','smarthome':'Smart Home','natverksinstallation':'Nätverksinstallation',
  'kameraovervakning':'Kameraövervakning','solceller':'Solceller','porttelefon':'Porttelefon',
  'rivning-badrum':'Rivning badrum','rivning-kok':'Rivning kök','bortforsling':'Bortforsling',
  'montera-tv-pa-vagg':'Montera TV på vägg','installera-akustikpanel':'Installera akustikpanel',
  'platsbyggd-garderob':'Platsbyggd garderob','platsbyggd-bokhylla':'Platsbyggd bokhylla',
  'montera-spotlights':'Montera spotlights','installera-laddbox-hemma':'Installera laddbox hemma',
  'bygga-altan':'Bygga altan','montera-koksflakt':'Montera köksfläkt',
  'installera-golvvarme':'Installera golvvärme','bygga-bastu':'Bygga bastu',
  'montera-markis':'Montera markis','installera-varmepump':'Installera värmepump',
  'renovera-trapp':'Renovera trapp','bygga-carport':'Bygga carport',
  'montera-takfonster':'Montera takfönster','bygga-utekok':'Bygga utekök',
  'bygga-friggebod':'Bygga friggebod','montera-persienner':'Montera persienner',
  'installera-solceller-hem':'Installera solceller hem','bygga-plank':'Bygga plank',
  'dorrlas':'Dörrlås',
};

// ─── Area slug → display name ───
export const AREAS = {
  'stockholm':'Stockholm','bromma':'Bromma','hagersten':'Hägersten',
  'kungsholmen':'Kungsholmen','sodermalm':'Södermalm','vasastan':'Vasastan',
  'ostermalm':'Östermalm','danderyd':'Danderyd','ekero':'Ekerö',
  'haninge':'Haninge','huddinge':'Huddinge','jarfalla':'Järfälla',
  'jarna':'Järna','lidingo':'Lidingö','marsta':'Märsta',
  'nacka':'Nacka','norrtalje':'Norrtälje','nykvarn':'Nykvarn',
  'nynashamn':'Nynäshamn','salem':'Salem','sigtuna':'Sigtuna',
  'sollentuna':'Sollentuna','solna':'Solna','sundbyberg':'Sundbyberg',
  'sodertalje':'Södertälje','tyreso':'Tyresö','taby':'Täby',
  'upplands-vasby':'Upplands Väsby','upplands-bro':'Upplands-Bro',
  'vallentuna':'Vallentuna','vaxholm':'Vaxholm','varmdo':'Värmdö',
  'akersberga':'Åkersberga','botkyrka':'Botkyrka',
  'uppsala':'Uppsala','knivsta':'Knivsta','enkoping':'Enköping',
  'tierp':'Tierp','osthammar':'Östhammar','storvreta':'Storvreta',
  'bjorklinge':'Björklinge','balinge':'Bälinge','vattholma':'Vattholma',
  'alsike':'Alsike','granby':'Gränby','savja':'Sävja',
  'eriksberg':'Eriksberg','gottsunda':'Gottsunda','sunnersta':'Sunnersta',
  'skyttorp':'Skyttorp','lovstalot':'Lövstalöt','gamla-uppsala':'Gamla Uppsala',
  'ultuna':'Ultuna',
};

// ─── sv→en slug mapping for hreflang ───
export const SV_TO_EN_SERVICE = {
  'snickare':'carpenter','elektriker':'electrician','vvs':'plumbing','malare':'painter',
  'tradgard':'garden','stad':'cleaning','markarbeten':'groundwork','montering':'assembly',
  'flytt':'moving','tekniska-installationer':'technical-installations',
  'koksmontering':'kitchen-installation','mobelmontering':'furniture-assembly',
  'badrumsrenovering':'bathroom-renovation','koksrenovering':'kitchen-renovation',
  'altanbygge':'deck-building','fasadmalning':'exterior-painting',
  'inomhusmalning':'interior-painting','golvlaggning':'flooring-installation',
  'elinstallation':'electrical-installation','rivning':'demolition',
};
