/**
 * Shared SEO data for generate-seo-inline.mjs
 * Service slug → display name (Swedish), area slug → display name, sv→en mapping
 */

// ─── Service slug → display name (Swedish) ───
export const SERVICES = {
  'snickare':'Snickare','elektriker':'Elektriker','vvs':'VVS','malare':'Målare',
  'tradgard':'Trädgård','stad':'Städ','markarbeten':'Markarbeten','montering':'Montering',
  'flytt':'Flytt','tekniska-installationer':'Tekniska installationer',
  'koksmontering':'Köksmontering','mobelmontering':'Möbelmontering',
  'badrumsrenovering':'Badrumsrenovering','koksrenovering':'Köksrenovering',
  'altanbygge':'Altanbygge','fasadmalning':'Fasadmålning','inomhusmalning':'Inomhusmålning',
  'golvlaggning':'Golvläggning','elinstallation':'Elinstallation','rivning':'Rivning',
  'totalrenovering':'Totalrenovering','renovering':'Renovering','hantverkare':'Hantverkare',
  'byggfirma':'Byggfirma','byggtjanster':'Byggtjänster','husrenovering':'Husrenovering',
  'villarenovering':'Villarenovering','lagenhetsrenovering':'Lägenhetsrenovering',
  'ombyggnad':'Ombyggnad','utbyggnad':'Utbyggnad','tillbyggnad':'Tillbyggnad',
  'fonsterbyte':'Fönsterbyte','dorrbyte':'Dörrbyte','fasadrenovering':'Fasadrenovering',
  'trapprenovering':'Trapprenovering','taklaggning':'Takläggning','takbyte':'Takbyte',
  'takrenovering':'Takrenovering','verandarenovering':'Verandarenovering',
  'entrerenoverning':'Entrérenoverning','vardagsrumsrenovering':'Vardagsrumsrenovering',
  'sovrumsrenovering':'Sovrumsrenovering','kontorsbygge':'Kontorsbygge',
  'bostadsanpassning':'Bostadsanpassning','platsbyggt':'Platsbyggt',
  'kok':'Kök','koksbyte':'Köksbyte','ikea-koksmontage':'IKEA-köksmontage',
  'koksinstallation':'Köksinstallation','koksdesign':'Köksdesign','nytt-kok':'Nytt kök',
  'koksluckor':'Köksluckor','bankskiva':'Bänkskiva','platsbyggt-kok':'Platsbyggt kök',
  'koksplanering':'Köksplanering','vitvaruinstallation-kok':'Vitvaruinstallation kök',
  'diskbanksbyte':'Diskbänksbyte','koksbelysning':'Köksbelysning','koksflakt':'Köksfläkt',
  'stankskydd':'Stänkskydd','badrum':'Badrum','badrumskakel':'Badrumskakel',
  'plattsattning':'Plattsättning','tatskikt':'Tätskikt','wc-renovering':'WC-renovering',
  'duschrum':'Duschrum','duschvagg':'Duschvägg','badrumsinredning':'Badrumsinredning',
  'tvattrum':'Tvättrum','badrumsgolv':'Badrumsgolv',
  'elarbeten':'Elarbeten','elreparation':'Elreparation','laddbox':'Laddbox',
  'laddboxinstallation':'Laddboxinstallation','sakringsbyte':'Säkringsbyte',
  'belysning':'Belysning','elcentral':'Elcentral','eljour':'Eljour',
  'lampmontering':'Lampmontering','spotlights':'Spotlights','elbesiktning':'Elbesiktning',
  'jordfelsbrytare':'Jordfelsbrytare',
  'vvs-arbeten':'VVS-arbeten','rorjour':'Rörjour','rorarbeten':'Rörarbeten',
  'varmepump':'Värmepump','vattenlas':'Vattenlås','avlopp':'Avlopp',
  'golvvarme':'Golvvärme','vattenbatteri':'Vattenbatteri','blandarbyte':'Blandarbyte',
  'radiatorbyte':'Radiatorbyte',
  'malning':'Målning','tapetsering':'Tapetsering','spackling':'Spackling',
  'lackering':'Lackering','fonstermalning':'Fönstermålning','takmalning':'Takmålning',
  'trappmalning':'Trappmålning','snickerimlaning':'Snickerimålning',
  'golvslipning':'Golvslipning','parkettlaggning':'Parkettläggning',
  'laminatgolv':'Laminatgolv','vinylgolv':'Vinylgolv','klinkergolv':'Klinkergolv',
  'epoxigolv':'Epoxigolv','golvbyte':'Golvbyte',
  'tradgardsanlaggning':'Trädgårdsanläggning','tradgardsskotsel':'Trädgårdsskötsel',
  'grasklippning':'Gräsklippning','hackklippning':'Häckklippning',
  'tradbeskaring':'Trädbeskärning','tradgardsdesign':'Trädgårdsdesign',
  'stenlaggning-tradgard':'Stenläggning trädgård','buskrojning':'Buskröjning',
  'dranering':'Dränering','schaktning':'Schaktning','plattlaggning':'Plattläggning',
  'stenlaggning':'Stenläggning','asfaltering':'Asfaltering','murverk':'Murverk',
  'uppfart':'Uppfart','garageuppfart':'Garageuppfart',
  'hemstad':'Hemstäd','flyttstad':'Flyttstäd','byggstad':'Byggstäd',
  'fonsterputs':'Fönsterputs','storstadning':'Storstädning','kontorsstad':'Kontorsstäd',
  'dodsbo':'Dödsbo','trappstad':'Trappstäd',
  'garderobsmontering':'Garderobsmontering','tv-montering':'TV-montering',
  'persiennmontering':'Persiennmontering','hyllmontering':'Hyllmontering',
  'ikeamontering':'IKEA-montering','dorrmontering':'Dörrmontering',
  'flytthjalp':'Flytthjälp','packhjalp':'Packhjälp','kontorsflytt':'Kontorsflytt',
  'magasinering':'Magasinering','pianoflytt':'Pianoflytt',
  'larm':'Larm','smarthome':'Smart Home','natverksinstallation':'Nätverksinstallation',
  'kameraovervakning':'Kameraövervakning','solceller':'Solceller','porttelefon':'Porttelefon',
  'rivning-badrum':'Rivning badrum','rivning-kok':'Rivning kök','bortforsling':'Bortforsling',
  'montera-tv-pa-vagg':'Montera TV på vägg','installera-akustikpanel':'Installera akustikpanel',
  'platsbyggd-garderob':'Platsbyggd garderob','platsbyggd-bokhylla':'Platsbyggd bokhylla',
  'montera-spotlights':'Montera spotlights','installera-laddbox-hemma':'Installera laddbox hemma',
  'bygga-altan':'Bygga altan','montera-koksflakt':'Montera köksfläkt',
  'installera-golvvarme':'Installera golvvärme','bygga-bastu':'Bygga bastu',
  'montera-markis':'Montera markis','installera-varmepump':'Installera värmepump',
  'renovera-trapp':'Renovera trapp','bygga-carport':'Bygga carport',
  'montera-takfonster':'Montera takfönster','bygga-utekok':'Bygga utekök',
  'bygga-friggebod':'Bygga friggebod','montera-persienner':'Montera persienner',
  'installera-solceller-hem':'Installera solceller hem','bygga-plank':'Bygga plank',
  'dorrlas':'Dörrlås',
};

// ─── Area slug → display name ───
export const AREAS = {
  'stockholm':'Stockholm','bromma':'Bromma','hagersten':'Hägersten',
  'kungsholmen':'Kungsholmen','sodermalm':'Södermalm','vasastan':'Vasastan',
  'ostermalm':'Östermalm','danderyd':'Danderyd','ekero':'Ekerö',
  'haninge':'Haninge','huddinge':'Huddinge','jarfalla':'Järfälla',
  'jarna':'Järna','lidingo':'Lidingö','marsta':'Märsta',
  'nacka':'Nacka','norrtalje':'Norrtälje','nykvarn':'Nykvarn',
  'nynashamn':'Nynäshamn','salem':'Salem','sigtuna':'Sigtuna',
  'sollentuna':'Sollentuna','solna':'Solna','sundbyberg':'Sundbyberg',
  'sodertalje':'Södertälje','tyreso':'Tyresö','taby':'Täby',
  'upplands-vasby':'Upplands Väsby','upplands-bro':'Upplands-Bro',
  'vallentuna':'Vallentuna','vaxholm':'Vaxholm','varmdo':'Värmdö',
  'akersberga':'Åkersberga','botkyrka':'Botkyrka',
  'uppsala':'Uppsala','knivsta':'Knivsta','enkoping':'Enköping',
  'tierp':'Tierp','osthammar':'Östhammar','storvreta':'Storvreta',
  'bjorklinge':'Björklinge','balinge':'Bälinge','vattholma':'Vattholma',
  'alsike':'Alsike','granby':'Gränby','savja':'Sävja',
  'eriksberg':'Eriksberg','gottsunda':'Gottsunda','sunnersta':'Sunnersta',
  'skyttorp':'Skyttorp','lovstalot':'Lövstalöt','gamla-uppsala':'Gamla Uppsala',
  'ultuna':'Ultuna',
};

// ─── sv→en slug mapping for hreflang ───
export const SV_TO_EN_SERVICE = {
  'snickare':'carpenter','elektriker':'electrician','vvs':'plumbing','malare':'painter',
  'tradgard':'garden','stad':'cleaning','markarbeten':'groundwork','montering':'assembly',
  'flytt':'moving','tekniska-installationer':'technical-installations',
  'koksmontering':'kitchen-installation','mobelmontering':'furniture-assembly',
  'badrumsrenovering':'bathroom-renovation','koksrenovering':'kitchen-renovation',
  'altanbygge':'deck-building','fasadmalning':'exterior-painting',
  'inomhusmalning':'interior-painting','golvlaggning':'flooring-installation',
  'elinstallation':'electrical-installation','rivning':'demolition',
};

// ─── Guide excerpts for pre-rendering (intro text per slug) ───
export const GUIDE_EXCERPTS = {
  'snickare': { sv: 'En professionell snickare hjälper dig med allt från köksrenovering till altanbygge. Lär dig vad du bör tänka på innan du anlitar snickare.', en: 'A professional carpenter helps with everything from kitchen renovation to deck building.' },
  'koksrenovering': { sv: 'Planerar du köksrenovering? Här går vi igenom kostnader, tidsplan och vad som ingår i en komplett köksrenovering.', en: 'Planning a kitchen renovation? Here we cover costs, timeline and what is included.' },
  'badrumsrenovering': { sv: 'Badrumsrenovering kräver GVK-auktoriserade hantverkare för tätskikt. Läs om kostnader, tidsplan och vanliga misstag.', en: 'Bathroom renovation requires certified waterproofing. Read about costs and common mistakes.' },
  'altanbygge': { sv: 'Drömmer du om en ny altan? Här får du veta allt om kostnader, material och bygglov för altanbygge.', en: 'Dreaming of a new deck? Learn about costs, materials and building permits.' },
  'koksmontering': { sv: 'Köksmontering kräver precision och erfarenhet. Läs om vad som ingår och vad du bör tänka på.', en: 'Kitchen assembly requires precision. Read about what is included and what to consider.' },
  'totalrenovering': { sv: 'En totalrenovering förvandlar hela bostaden. Här guidar vi dig genom processen.', en: 'A full renovation transforms your entire home.' },
  'husrenovering': { sv: 'Husrenovering kan innebära allt från ytskikt till stomme. Få koll på kostnader och planering.', en: 'House renovation can range from surfaces to structural work.' },
  'golvlaggning': { sv: 'Rätt golv gör hela skillnaden. Läs om olika golvtyper, kostnader och vad du bör tänka på.', en: 'The right floor makes all the difference. Read about floor types and costs.' },
  'golvslipning': { sv: 'Golvslipning ger ditt trägolv nytt liv. Lär dig om processen, kostnader och skillnaden mellan lackning och oljning.', en: 'Floor sanding gives your wooden floor new life.' },
  'parkettlaggning': { sv: 'Parkettläggning ger ett elegant och tidlöst golv. Jämför olika parketttyper och kostnader.', en: 'Parquet installation gives an elegant and timeless floor.' },
  'laminatgolv': { sv: 'Laminatgolv är prisvärt och tåligt. Läs om kostnader och vilken typ som passar bäst.', en: 'Laminate flooring is affordable and durable.' },
  'vinylgolv': { sv: 'Vinylgolv är vattentåligt och slitstark — perfekt för kök, hall och badrum.', en: 'Vinyl flooring is waterproof and durable — perfect for kitchens and bathrooms.' },
  'golvbyte': { sv: 'Dags att byta golv? Vi guidar dig genom rivning, val av nytt golv och kostnader.', en: 'Time for new floors? We guide you through removal and costs.' },
  'malare': { sv: 'En professionell målare ger ett felfritt resultat. Läs om kostnader för målning.', en: 'A professional painter gives a flawless result.' },
  'fasadmalning': { sv: 'Fasadmålning skyddar och förskönar ditt hus. Lär dig om rätt färg och kostnader.', en: 'Exterior painting protects and beautifies your house.' },
  'inomhusmalning': { sv: 'Inomhusmålning fräschar upp hemmet snabbt. Få koll på kostnader per rum.', en: 'Interior painting freshens up your home quickly.' },
  'tapetsering': { sv: 'Tapetsering ger en helt ny känsla i rummet. Läs om kostnader och tips.', en: 'Wallpapering transforms any room.' },
  'markarbeten': { sv: 'Markarbeten inkluderar schaktning, dränering och planering. Få koll på kostnader.', en: 'Groundwork includes excavation, drainage and grading.' },
  'plattlaggning': { sv: 'Plattläggning skapar snygga och hållbara utomhusytor.', en: 'Paving creates beautiful outdoor surfaces.' },
  'stenlaggning': { sv: 'Stenläggning ger eleganta och hållbara ytor utomhus.', en: 'Stone laying creates elegant outdoor surfaces.' },
  'dranering': { sv: 'Dränering skyddar husgrunden mot fukt och vattenskador.', en: 'Drainage protects the foundation from moisture.' },
  'montering': { sv: 'Professionell montering av möbler, garderobar, TV och hyllor.', en: 'Professional assembly of furniture, wardrobes and shelves.' },
  'rivning': { sv: 'Rivning av badrum, kök och väggar — läs om kostnader och tidsplan.', en: 'Demolition of bathrooms, kitchens and walls.' },
  'renovering': { sv: 'Renovering kan förändra hela hemmet. Få koll på kostnader och ROT-avdrag.', en: 'Renovation can transform your entire home.' },
  'villarenovering': { sv: 'Villarenovering kräver noggrann planering. Läs om kostnader.', en: 'Villa renovation requires careful planning.' },
  'lagenhetsrenovering': { sv: 'Lägenhetsrenovering kräver ofta samordning med BRF.', en: 'Apartment renovation often requires coordination with the housing association.' },
  'fonsterbyte': { sv: 'Fönsterbyte sänker energikostnaden och förbättrar komforten.', en: 'Window replacement reduces energy costs and improves comfort.' },
  'taklaggning': { sv: 'Takläggning skyddar ditt hus i 30–50 år.', en: 'Roofing protects your house for 30–50 years.' },
  'takbyte': { sv: 'Takbyte är en stor investering som skyddar huset.', en: 'Roof replacement is a major investment protecting your house.' },
  'fasadrenovering': { sv: 'Fasadrenovering förbättrar utseende och skyddar huset.', en: 'Facade renovation improves appearance and protects the house.' },
  'tillbyggnad': { sv: 'Tillbyggnad ger mer boyta. Läs om kostnader och bygglov.', en: 'An extension adds living space.' },
  'ombyggnad': { sv: 'Ombyggnad kan innebära planlösningsändringar och vindsinredning.', en: 'Conversion can include layout changes and attic conversion.' },
  'bygga-altan': { sv: 'Att bygga altan ger mer boarea utomhus.', en: 'Building a deck extends outdoor living space.' },
  'bygga-bastu': { sv: 'En egen bastu höjer livskvaliteten och bostadsvärdet.', en: 'A private sauna increases quality of life and property value.' },
  'bygga-carport': { sv: 'Carport skyddar bilen och höjer fastighetsvärdet.', en: 'A carport protects your car and increases property value.' },
  'bygga-friggebod': { sv: 'Friggebod (max 15 kvm) kräver inget bygglov.', en: 'A garden shed (max 15 sqm) needs no permit.' },
  'bygga-utekok': { sv: 'Utekök förlänger sommarsäsongen.', en: 'An outdoor kitchen extends the summer season.' },
  'bygga-plank': { sv: 'Plank och staket ger insynsskydd och ramar in tomten.', en: 'Fencing provides privacy and frames your property.' },
  'platsbyggd-garderob': { sv: 'Platsbyggd garderob utnyttjar varje millimeter.', en: 'A custom wardrobe uses every millimeter.' },
  'platsbyggd-bokhylla': { sv: 'Platsbyggd bokhylla ger rummet karaktär.', en: 'A custom bookshelf adds character.' },
  'renovera-trapp': { sv: 'Trapprenovering ger ny look utan att byta hela trappan.', en: 'Stair renovation gives a new look without full replacement.' },
  'trapprenovering': { sv: 'Trapprenovering ger ny look och ökad säkerhet.', en: 'Stair renovation gives a new look and increased safety.' },
  'dorrbyte': { sv: 'Dörrbyte förbättrar utseende och säkerhet.', en: 'Door replacement improves appearance and security.' },
  'hantverkare': { sv: 'Vad kostar hantverkare? Jämför timpriser.', en: 'What does a craftsman cost? Compare rates.' },
  'byggfirma': { sv: 'Att anlita byggfirma ger projektledning och garanti.', en: 'Hiring a construction company provides project management.' },
};

// ─── Review templates for pre-rendering ───
// Compact review data: names + templates for generating unique reviews per area/service
export const REVIEW_NAMES = [
  'Emma A.','Erik B.','Anna G.','Johan H.','Sofia K.','Lars M.','Maria N.','Anders P.',
  'Ali R.','Fatima S.','Chen T.','Pawel V.','Gustav W.','Lena Z.','Oscar C.','Elin D.',
  'Viktor E.','Klara F.','David J.','Sara L.'
];
export const REVIEW_TEMPLATES_SV = [
  'Fantastisk {service} i {area}! Professionella och punktliga. Rekommenderas starkt.',
  'Bästa hantverkarna vi anlitat i {area}. Snyggt jobb och bra kommunikation!',
  'Mycket nöjd med arbetet i vårt hem i {area}. Kommer definitivt anlita igen!',
  'ROT-avdraget ordnades smidigt. Supernöjd kund i {area}!',
  'Överträffade våra förväntningar. Prisvärt och kvalitativt arbete i {area}.',
  'Allt gick smidigt från offert till färdigt resultat. Toppen!',
  'Proffsigt team som levererade i tid i {area}. Stort tack!',
  'Snabba, effektiva och städade efter sig. Perfekt {service}!',
];
export const REVIEW_TEMPLATES_EN = [
  'Amazing {service} in {area}! Professional and punctual. Highly recommended.',
  'Best contractors we have hired in {area}. Great work and communication!',
  'Very satisfied with the work in our home in {area}. Will definitely hire again!',
  'ROT deduction handled smoothly. Super happy customer in {area}!',
  'Exceeded our expectations. Great value and quality work in {area}.',
  'Everything went smoothly from quote to finished result. Excellent!',
  'Professional team that delivered on time in {area}. Thank you!',
  'Fast, efficient and cleaned up afterwards. Perfect {service}!',
];
