INSERT INTO service_addons (service_id, title_sv, description_sv, addon_price, price_unit, is_active, sort_order, icon, rot_eligible, rut_eligible) VALUES
('el-9', 'Kabeldragning för TV-uttag', 'Dra ny elkabel från elcentral till TV-plats med nätverks- och antennutag', 2500, 'kr', true, 1, 'cable', true, false),
('el-9', 'Dold kabelkanal bakom vägg', 'Installation av dold kabelkanal för riktigt snyggt resultat', 1800, 'kr', true, 2, 'eye-off', true, false),
('el-8', 'Bortforsling av gammal elutrustning', 'Vi återvinner gamla lampor och uttag miljövänligt', 400, 'kr', true, 1, 'recycle', true, false),
('vvs-2', 'Bortforsling av gammal toalett', 'Vi tar hand om och återvinner din gamla toalett', 600, 'kr', true, 1, 'trash-2', true, false),
('vvs-2', 'Montage av kundens toalett', 'Installation av toalett du köpt själv', 1200, 'kr', true, 2, 'wrench', true, false),
('vvs-1', 'Bortforsling av gammal blandare', 'Vi tar hand om gamla kranar', 300, 'kr', true, 1, 'trash-2', true, false),
('vvs-13', 'Bortforsling av gammalt badrum', 'Vi river och fraktar bort allt gammalt material', 4500, 'kr', true, 1, 'truck', true, false),
('vvs-13', 'Byggstäd efter renovering', 'Grundlig städning efter badrumsrenovering', 2500, 'kr', true, 2, 'sparkles', true, false),
('vvs-4', 'Installation av kundens diskmaskin', 'Montage och anslutning av diskmaskin du köpt själv', 1500, 'kr', true, 1, 'wrench', true, false),
('vvs-4', 'Bortforsling av gammal diskmaskin', 'Vi tar hand om din gamla diskmaskin', 500, 'kr', true, 2, 'trash-2', true, false),
('snickeri-1', 'Bortforsling av gamla möbler', 'Vi tar hand om gamla garderober och möbler', 1200, 'kr', true, 1, 'truck', true, false),
('snickeri-1', 'LED-belysning i garderob', 'Automatisk LED-belysning som tänds när du öppnar', 1800, 'kr', true, 2, 'lightbulb', true, false),
('snickeri-2', 'Bortforsling av gamla köksluckor', 'Vi tar hand om gamla köksluckor och bänkskivor', 1500, 'kr', true, 1, 'trash-2', true, false),
('snickeri-2', 'Byggstäd efter montering', 'Städning efter köksmontage', 1200, 'kr', true, 2, 'sparkles', true, false),
('malning-innervagg', 'Bortforsling av tapetavfall', 'Vi tar hand om tapeter och färgburkar', 500, 'kr', true, 1, 'trash-2', true, false),
('malning-innervagg', 'Städning efter målning', 'Grundlig städning efter målarjobb', 800, 'kr', true, 2, 'sparkles', true, false),
('montering-1', 'Bortforsling av kartonger', 'Vi tar hand om IKEA-kartonger och förpackningar', 400, 'kr', true, 1, 'package', true, false),
('montering-1', 'Bortforsling av gamla möbler', 'Vi tar hand om gamla möbler som ska bort', 800, 'kr', true, 2, 'truck', true, false),
('montering-4', 'Installation av kundens vitvaror', 'Montage och anslutning av vitvaror du köpt själv', 1200, 'kr', true, 1, 'wrench', true, false),
('montering-4', 'Bortforsling av gammal vitvara', 'Vi tar hand om gamla kyl, frys, ugn', 700, 'kr', true, 2, 'trash-2', true, false),
('tradgard-1', 'Bortforsling av gräsklipp', 'Vi tar hand om gräsavfall och komposterar', 400, 'kr', true, 1, 'leaf', false, true),
('tradgard-2', 'Bortforsling av häckavfall', 'Vi tar hand om grenar och löv', 600, 'kr', true, 1, 'tree-pine', false, true),
('flytt-1', 'Bortforsling av möbler', 'Vi tar hand om möbler som inte ska med', 1500, 'kr', true, 1, 'truck', false, true),
('flytt-1', 'Demontering av möbler', 'Vi plockar isär stora möbler inför flytt', 800, 'kr', true, 2, 'wrench', false, true),
('flytt-1', 'Montering på nya stället', 'Vi monterar ihop möbler på nya adressen', 1200, 'kr', true, 3, 'plus', false, true),
('flytt-2', 'Packmaterial', 'Kartonger, bubbelplast och tejp', 800, 'kr', true, 1, 'package', false, true),
('flytt-3', 'Flyttstädning', 'Flyttstäd enligt Svensk standard', 2500, 'kr', true, 1, 'sparkles', false, true),
('stadning-1', 'Fönsterputs som tillägg', 'Putsning av alla fönster invändigt', 500, 'kr', true, 1, 'square', false, true),
('stadning-1', 'Ugnsrengöring', 'Djuprengöring av ugn', 400, 'kr', true, 2, 'flame', false, true),
('stadning-2', 'Fönsterputs in och ut', 'Kompletta fönsterputsning', 800, 'kr', true, 1, 'square', false, true),
('stadning-3', 'Bortforsling av byggavfall', 'Vi tar hand om byggavfall och återvinner', 1500, 'kr', true, 1, 'truck', false, true),
('stadning-3', 'Extra djuprengöring', 'Extra grundlig rengöring för tuffa ytor', 1200, 'kr', true, 2, 'sparkles', false, true)
ON CONFLICT (id) DO NOTHING