-- Insert Stockholm/Solna reference project (corrected)
INSERT INTO public.reference_projects (
  title,
  description,
  location,
  category,
  features,
  title_sv,
  title_en,
  description_sv,
  description_en,
  location_sv,
  location_en,
  category_sv,
  category_en,
  features_sv,
  features_en,
  duration,
  completed_date,
  price_amount,
  rot_saving_amount,
  rut_saving_amount,
  rating,
  client_initials,
  images,
  is_featured,
  is_active,
  sort_order
) VALUES (
  'Lyxig Totalrenovering med Smart Belysning',
  'En imponerande totalrenovering av en klassisk bostad i Solna, Stockholm. Projektet omfattar en platsbyggd bar med exklusiva detaljer, genomgående Philips Hue spotlights i vardagsrum, kök och hall, samt skräddarsydd förvaring. I sovrummet har vi skapat ett elegant sminkbord/skrivbord med platsbyggd spegel omgiven av Philips Hue-belysning. Marmor används genomgående för bänkskivor och detaljer, vilket ger en lyxig och tidlös känsla. En flytande säng med platsbyggd konstruktion kompletterar det moderna och stilrena utseendet. Detta projekt visar hur klassisk svensk arkitektur kan kombineras med modern smart home-teknologi för ett resultat som är både praktiskt och estetiskt tilltalande.',
  'Solna, Stockholm',
  'Vardagsrum',
  ARRAY[
    'Platsbyggd bar med premiumfinish',
    'Philips Hue spotlights genom hela bostaden',
    'Sminkbord med smart spegelbelsning',
    'Marmorskivor och detaljer',
    'Platsbyggd flytande säng',
    'Skräddarsydd förvaring',
    'Smart hem-integration',
    'Totalrenovering'
  ],
  'Lyxig Totalrenovering med Smart Belysning',
  'Luxury Complete Renovation with Smart Lighting',
  'En imponerande totalrenovering av en klassisk bostad i Solna, Stockholm. Projektet omfattar en platsbyggd bar med exklusiva detaljer, genomgående Philips Hue spotlights i vardagsrum, kök och hall, samt skräddarsydd förvaring. I sovrummet har vi skapat ett elegant sminkbord/skrivbord med platsbyggd spegel omgiven av Philips Hue-belysning. Marmor används genomgående för bänkskivor och detaljer, vilket ger en lyxig och tidlös känsla. En flytande säng med platsbyggd konstruktion kompletterar det moderna och stilrena utseendet. Detta projekt visar hur klassisk svensk arkitektur kan kombineras med modern smart home-teknologi för ett resultat som är både praktiskt och estetiskt tilltalande.',
  'An impressive complete renovation of a classic residence in Solna, Stockholm. The project includes a custom-built bar with exclusive details, throughout Philips Hue spotlights in living room, kitchen and hallway, as well as tailored storage solutions. In the bedroom, we created an elegant vanity/desk with a custom-built mirror surrounded by Philips Hue lighting. Marble is used throughout for countertops and details, providing a luxurious and timeless feel. A floating bed with custom construction completes the modern and sleek appearance. This project demonstrates how classic Swedish architecture can be combined with modern smart home technology for a result that is both practical and aesthetically pleasing.',
  'Solna, Stockholm',
  'Solna, Stockholm',
  'Vardagsrum',
  'Living Room',
  ARRAY[
    'Platsbyggd bar med premiumfinish',
    'Philips Hue spotlights genom hela bostaden',
    'Sminkbord med smart spegelbelsning',
    'Marmorskivor och detaljer',
    'Platsbyggd flytande säng',
    'Skräddarsydd förvaring',
    'Smart hem-integration',
    'Totalrenovering'
  ],
  ARRAY[
    'Custom-built bar with premium finish',
    'Philips Hue spotlights throughout',
    'Vanity desk with smart mirror lighting',
    'Marble countertops and details',
    'Custom-built floating bed',
    'Tailored storage solutions',
    'Smart home integration',
    'Complete renovation'
  ],
  '1.5 månader',
  '2025-01-01',
  250000,
  75000,
  0,
  5,
  'M.E',
  ARRAY[
    '/reference-projects/solna-renovation-bar.jpg',
    '/reference-projects/solna-renovation-kitchen.jpg',
    '/reference-projects/solna-renovation-construction.jpg',
    '/reference-projects/solna-renovation-lighting.jpg',
    '/reference-projects/solna-renovation-demolition.jpg',
    '/reference-projects/solna-renovation-bedroom.jpg',
    '/reference-projects/solna-renovation-vanity.jpg',
    '/reference-projects/solna-renovation-mirror.jpg',
    '/reference-projects/solna-renovation-living-room.jpg',
    '/reference-projects/solna-renovation-storage.jpg'
  ],
  true,
  true,
  0
);