INSERT INTO reference_projects (
  title, title_sv, title_en,
  description, description_sv, description_en,
  location, location_sv, location_en,
  category, category_sv, category_en,
  features, features_sv, features_en,
  client_initials, rating, duration,
  completed_date, price_amount, rot_saving_amount, rut_saving_amount,
  images, thumbnail_image,
  is_featured, is_active, sort_order
) VALUES (
  'Garderobsbyte & Hemfixar i Liljeholmen',
  'Garderobsbyte & Hemfixar i Liljeholmen',
  'Wardrobe Replacement & Home Repairs in Liljeholmen',
  'Kunden i Liljeholmen kontaktade oss med två akuta problem: en balkongdörr som inte längre gick att stänga ordentligt på grund av utslitna och trasiga gångjärn, samt gamla garderober i hallen som var i behov av totalrenovering. Vi började med att noggrant demontera de gamla garderoberna och transporterade bort allt material. Därefter monterade vi nya, moderna skjutdörrsgarderober som maximerade förvaringsutrymmet och gav hallen ett helt nytt, fräscht utseende. Balkongdörren fick nya, robusta gångjärn och justerades in perfekt — nu stänger den tätt och smidigt igen. Kunden var överlycklig med resultatet och uppskattade särskilt den snabba och professionella hanteringen av båda projekten.',
  'Kunden i Liljeholmen kontaktade oss med två akuta problem: en balkongdörr som inte längre gick att stänga ordentligt på grund av utslitna och trasiga gångjärn, samt gamla garderober i hallen som var i behov av totalrenovering. Vi började med att noggrant demontera de gamla garderoberna och transporterade bort allt material. Därefter monterade vi nya, moderna skjutdörrsgarderober som maximerade förvaringsutrymmet och gav hallen ett helt nytt, fräscht utseende. Balkongdörren fick nya, robusta gångjärn och justerades in perfekt — nu stänger den tätt och smidigt igen. Kunden var överlycklig med resultatet och uppskattade särskilt den snabba och professionella hanteringen av båda projekten.',
  'The customer in Liljeholmen contacted us with two urgent issues: a balcony door that could no longer close properly due to worn and broken hinges, and old hallway wardrobes in need of a complete renovation. We started by carefully dismantling the old wardrobes and hauling away all materials. Then we installed new, modern sliding-door wardrobes that maximized storage space and gave the hallway a completely fresh look. The balcony door received new, robust hinges and was adjusted to perfection — it now closes tightly and smoothly again. The customer was thrilled with the result and especially appreciated the fast and professional handling of both projects.',
  'Liljeholmen, Stockholm',
  'Liljeholmen, Stockholm',
  'Liljeholmen, Stockholm',
  'Hemfixar',
  'Hemfixar',
  'Home Repairs',
  ARRAY['Balkongdörrsreparation', 'Garderobsdemontering', 'Garderobsmontering', 'Gångjärnsbyte'],
  ARRAY['Balkongdörrsreparation', 'Garderobsdemontering', 'Garderobsmontering', 'Gångjärnsbyte'],
  ARRAY['Balcony Door Repair', 'Wardrobe Dismantling', 'Wardrobe Installation', 'Hinge Replacement'],
  'H.W',
  5,
  '2 dagar',
  '2025-05-15',
  18500,
  4625,
  0,
  ARRAY['/images/references/garderob.webp', '/images/references/garderob_hall.webp'],
  '/images/references/garderob.webp',
  true,
  true,
  1
);