
-- Insert 6 new door lock services
INSERT INTO public.services (id, category, title_sv, description_sv, title_en, description_en, base_price, price_unit, price_type, rot_eligible, rut_eligible, location, sub_category, is_active, sort_order, additional_categories, search_keywords)
VALUES
  ('montering-installera-smart-dorrlas', 'montering', 'Installera smart dörrlås', 'Installation av smarta dörrlås (Yale Doorman, Linus, Nuki m.fl.). Vi monterar och konfigurerar ditt nya smarta lås.', 'Install Smart Door Lock', 'Installation of smart door locks (Yale Doorman, Linus, Nuki etc.). We mount and configure your new smart lock.', 759, 'kr/h', 'hourly', true, false, 'inomhus', 'Dörrlås', true, 100, '{tekniska-installationer}', 'yale doorman, yale linus, smart lås, kodlås, dörrlås, assa, assa abloy, nuki, glue lock, digitalt lås, elektriskt lås, ytterdörr, säkerhet, hemmasäkerhet, nyckelfritt, smart dörrlås, bluetooth lås, danalock'),

  ('montering-installera-yale-doorman', 'montering', 'Installera Yale Doorman', 'Professionell installation av Yale Doorman (L3S Flex, Classic, V2N). Inkl. konfiguration av app och kod.', 'Install Yale Doorman', 'Professional installation of Yale Doorman (L3S Flex, Classic, V2N). Including app and code configuration.', 759, 'kr/h', 'hourly', true, false, 'inomhus', 'Dörrlås', true, 101, '{tekniska-installationer}', 'yale doorman, yale doorman l3s, yale doorman flex, yale doorman classic, yale doorman v2n, yale doorman installation, yale doorman montering, yale doorman pris, smart dörrlås yale'),

  ('montering-installera-yale-linus', 'montering', 'Installera Yale Linus', 'Installation av Yale Linus smart lås. Passar de flesta dörrar utan borrning. Inkl. konfiguration.', 'Install Yale Linus', 'Installation of Yale Linus smart lock. Fits most doors without drilling. Including configuration.', 759, 'kr/h', 'hourly', true, false, 'inomhus', 'Dörrlås', true, 102, '{tekniska-installationer}', 'yale linus, yale linus installation, yale linus montering, yale linus pris, yale linus smart lock, yale linus l2, smart lås utan borrning'),

  ('montering-installera-kodlas', 'montering', 'Installera kodlås', 'Installation av kodlås på ytterdörr eller innerdörr. Vi anpassar efter din dörr och installerar säkert.', 'Install Code Lock', 'Installation of code locks on exterior or interior doors. We adapt to your door and install safely.', 759, 'kr/h', 'hourly', true, false, 'inomhus', 'Dörrlås', true, 103, '{tekniska-installationer}', 'kodlås, kodlås ytterdörr, kodlås innerdörr, kodlås installation, digitalt kodlås, knappsats lås, pinkodslas, kodlås montering'),

  ('montering-byta-cylinderlas', 'montering', 'Byta cylinderlås', 'Byte av cylinderlås i ytterdörr eller innerdörr. Vi hjälper med rätt cylinder och säker installation.', 'Replace Cylinder Lock', 'Replacement of cylinder locks in exterior or interior doors. We help with the right cylinder and safe installation.', 759, 'kr/h', 'hourly', true, false, 'inomhus', 'Dörrlås', true, 104, '{}', 'cylinderlås, byta lås, låsbyte, assa lås, byta cylinderlås, dörrlås byte, ytterdörr lås, säkerhetslås, låscylinder'),

  ('tekniska-installera-larm-dorrlas', 'tekniska-installationer', 'Installera larm och dörrlås-paket', 'Komplett installation av larm och smart dörrlås. Vi konfigurerar hela säkerhetspaketet.', 'Install Alarm and Door Lock Package', 'Complete installation of alarm and smart door lock. We configure the entire security package.', 759, 'kr/h', 'quote', true, false, 'inomhus', 'Säkerhet', true, 105, '{montering}', 'larm dörrlås, säkerhetspaket, larm installation, smart larm, hemlarm dörrlås, säkerhetssystem, larm och lås, komplett säkerhet');
